## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default

## *Time domain RFI
## ##########################################################################
#help: --tr, --time_rfi; default: True; choices: True, False; 
tr = True
#help: --tr_s_method_t; default: gaussian; smoothing method along time axis
tr_s_method_t = gaussian
#help: --tr_s_sigma_t; default: 10; 
tr_s_sigma_t = 10
#help: --tr_s_method_freq; default: gaussian; smoothing method along time freq
tr_s_method_freq = gaussian
#help: --tr_s_sigma_freq; default: 5; 
tr_s_sigma_freq = 5
#help: --tr_n_continue; default: 100; 
tr_n_continue = 100
#help: --tr_times; default: 6.0; 
tr_times = 6.0
#help: --tr_times_s; default: 1.5; 
tr_times_s = 1.5
#help: --ext_add; default: 0; extend rfi range
ext_add = 0
#help: --ext_frac; default: 0.0; between 0 and 1, extend rfi range
ext_frac = 0.0

## *Polarize RFI
## ##########################################################################
#help: --pr, --polar_rfi; default: True; choices: True, False; 
pr = True
#help: --pr_s_sigma; default: 5; gaussian smooth size for spectra smoothing along time axis
pr_s_sigma = 5
#help: --pr_times; default: 6; 
pr_times = 6
#help: --pr_times_s; default: 1; 
pr_times_s = 1

