## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --frange; default: [0, inf]; Limit frequence range
frange = [0, inf]
#help: --nproc, -n; default: 1; number of process used in fitting baseline
nproc = 10

## *select method used to fit standing wave
## ##########################################################################
#help: --method; default: sin_poly; choices: sin_poly, fft; method to fit standing wave
method = fft
#help: --nobld; default: False; choices: True, False; if True, use the spectra before bld to subtract standing wave and output file name will add 'nobld'
nobld = False
#help: --fpattern_nobld; default: None; if not specify, guess from the History recored in the fpath
#fpattern_nobld = 

##   preprocessing before fitting
#help: --s_method_t; default: none; choices: none, gaussian, boxcar, median; 
s_method_t = none
#help: --s_sigma_t; default: 5; 
s_sigma_t = 5
#help: --s_method_freq; default: none; choices: none, median, gaussian, boxcar; 
s_method_freq = none
#help: --s_sigma_freq; default: 5; 
s_sigma_freq = 5
#help: --average_every_freq; default: 0; 
average_every_freq = 0

## *parameters for --method sin_poly
## ##########################################################################:
## addition options for preprocessing before fitting
#help: --njoin; default: 10; join nspec along t
njoin = 10

## sinusoidal standing wave (sw) fitting
#help: --exclude_m; default: 0; 
exclude_m = 0
#help: --sin_f; default: 0.929; sin freq
sin_f = 0.929
#help: --deg; default: 1; baseline fit parameters
deg = 1

## *parameters for --method fft
## ##########################################################################:
## replace big RFI or sources firstly
#help: --rfi_method; default: near_ripple; choices: near_ripple; method to replace big RFI
rfi_method = near_ripple
#help: --mw_frange; default: [1419, 1422]; milky way freq range, or None
mw_frange = [1419, 1422]
#help: --rms_sigma; default: 6; gauss filter sigma to compute real rms
rms_sigma = 6
#help: --rms_frange; default: None; freq range to compute rms
#rms_frange = 
#help: --times_lower_thr; default: 4; above * times of rms will be lowered
times_lower_thr = 4
#help: --ext_freq; default: 1.3; extend freq range to replace (mhz)
ext_freq = 1.3
#help: --rfi_width_lim; default: 15; rfi should contain more channels than limit
rfi_width_lim = 15
#help: --ext_sec; default: 20; extend channel number of start and end of each section
ext_sec = 20

## phase space
#help: --sw_base; default: True; choices: True, False; if True, remove constant components
sw_base = True
#help: --sw_periods; default: ['1mhz', '2mhz', '0_04mhz']; choices: 1mhz, 2mhz, 0_04mhz; remove ripple (1mhz: 1.08mhz, 2mhz:1.92mhz, 0_04mhz: 0.039 mhz)
sw_periods = [1mhz, 2mhz, 0_04mhz]
#help: --check_2mhz; default: True; choices: True, False; if True, remove 2mhz from sw_periods except for Beam 6
check_2mhz = True
#help: --amp_thr_mean_factor; default: 1.05; above mean amptitude threshold will be chosed
amp_thr_mean_factor = 1.05
#help: --amp_thr_solo_factor; default: 1.4; above amptitude threshold will be chosed in every spec
amp_thr_solo_factor = 1.4
#help: --chan_wide; default: 5; channel numbers near 1mhz to be chosed (wide)
chan_wide = 5
#help: --chan_narr; default: 3; channel numbers near 1mhz to be chosed (narrow)
chan_narr = 3
#help: --choose_method; default: all; choices: all, interpolate; method to choose components in fft
choose_method = all

