## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default

## *frame correction
## ##########################################################################
#help: --frame; default: LSRK; choices: HELIOCEN, LSRK; Velocity Rest Frames, HELIOCEN or LSRK
frame = LSRK

## *after
## ##########################################################################
#help: --replace_rfi; default: True; choices: True, False; if True, replace spectra contaminated by rfi as np.nan
replace_rfi = True
#help: --merge_polar; default: True; choices: True, False; if True, average two polarization
merge_polar = True

