
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-07T18:32:35+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ad099e9396b9e2053c9c289abe5c85a1cd6deca",
 "version": "v1.3a3+2.g7ad099e.test"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
