# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_add_radec.ipynb (unless otherwise specified).

__all__ = ['get_nB', 'Replace_nB', 'gen_radec_file', 'get_radec']

# Cell
import os
import re
import sys


def get_nB(path):
    return int(re.findall(r'-M[0-1][0-9]', os.path.basename(path))[-1][2:])


def Replace_nB(path, nB):
    """
    replace the beam number of 'path' with the input nB
    """
    return os.path.join(os.path.dirname(path), re.sub(r'-M[0-1][0-9]', f"-M{nB:02d}", os.path.basename(path)))

# Cell
def gen_radec_file(file_spec, paras=[]):
    """
    generating ra dec for a specs_T file
    """
    import subprocess
    command = [sys.executable, '-m', 'hifast.radec', file_spec] + paras
    print('run:')
    print(' '.join(command))
    sys.stdout.flush()
    process = subprocess.Popen(
        command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # process.wait()
    print(*process.communicate())
    if process.returncode != 0:
        raise(ValueError(f'fail to generate the radec file of {file_spec}'))

# Cell
import h5py


def get_radec(file_spec, nB_radec=1):
    """
    load the ra dec of spectra in file_spec (*specs_T.hdf5)

    file_spec: str or h5py.File

    """
    if isinstance(file_spec, str):
        fs = h5py.File(file_spec, 'r')
        mjd = fs['mjd'][:]
    else:
        mjd = file_spec['mjd'][:]
        file_spec = file_spec.filename

    nB = get_nB(file_spec)
    # ra dec file
    file_radec = file_spec.rsplit('specs_T', 1)[0] + 'specs_T-radec.hdf5'
    #file_radec = re.findall(r'.*-specs_T', file_radec)+'-radec.hdf5'
    file_radec = Replace_nB(file_radec, nB_radec)
    f = h5py.File(file_radec, 'r')
    # check if mjd match
    mjd_match = False if len(mjd) != len(
        f['mjd'][:]) else (mjd == f['mjd'][:]).all()
    if not mjd_match:
        print('the mjd of spec file is not same with that in ', file_radec)
        sys.stdout.flush()
        file_radec_2 = Replace_nB(file_radec, nB)
        if not os.path.exists(file_radec_2):
            print('try to generate ', file_radec_2)
            sys.stdout.flush()
            header = f['Header'].attrs
            import json
            for key in header.keys():
                argv = json.loads(header[key])['argv']
                paras = argv.split()
                if os.path.basename(paras[0]) not in ['cli_radec.py', 'radec.py']:
                    continue
                else:
                    paras.pop(0)
                    for s in paras:
                        if '.hdf5' in s:
                            paras.remove(s)
            gen_radec_file(file_spec, paras)
            sys.stdout.flush()
        f.close()
        f = h5py.File(file_radec_2, 'r')
        print('using', file_radec_2)
        sys.stdout.flush()
    # check again
    mjd_match = False if len(mjd) != len(
        f['mjd'][:]) else (mjd == f['mjd'][:]).all()
    if not mjd_match:
        raise(ValueError(
            f'the mjd of spec file is not same with that in {file_radec_2} Abort...'))
    # load
    ra = f['ra'+'%d' % nB][:]
    dec = f['dec'+'%d' % nB][:]
    if 'is_extrapo' in f.keys():
        is_extrapo = f['is_extrapo'][:]
    else:
        is_extrapo = None
    f.close()
    return ra, dec, is_extrapo

# Cell
if __name__ == '__main__':
    import h5py
    import argparse
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument('fname',
                        help='file name')
#     parser.add_argument('-f', '--force', action='store_true',
#                         help='overwriting file if out file exists')
    parser.add_argument('--nB_radec', type=int, default=1,
                        help='Beam number of the radec file name')
#     parser.add_argument('--outdir',
#                         help='default is same with the input file')
    args = parser.parse_args()
    f = h5py.File(args.fname, 'r+')
    f['ra'], f['dec'], f['is_extrapo'] = get_radec(f, args.nB_radec)
    f.close()