# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S2-bld.ipynb (unless otherwise specified).

__all__ = ['IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract baseline', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature or flux file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")
parser.add_argument('--show_prog', type=bool_fun, choices=[True, False], default='True',
                    help='')

# group = parser.add_argument_group(f'*Flux\n{sep_line}')
# group.add_argument('--flux', type=bool_fun, choices=[True, False], default='False',
#                    help='if True, convert  the temperature to flux before subtract baseline')
# group.add_argument('--cali_fname', default='none',
#                    help='quasar calibration file name')

# baseline fitting
group = parser.add_argument_group(f'*BaseLine (set --method as none to skip this) \n{sep_line}')

rew_type = ['asym1', 'asym2', 'asym3', 'sym1',]
method = ['none']
method += ['PLS-'+r for r in rew_type]
method += ['poly-'+r for r in rew_type]
method += ['masPLS-'+r for r in rew_type]
method += ['asPLS',]
method += ['original']

group.add_argument('--method', default='arPLS', choices=method,
                   help='method used to fit baseline, if set as none, skip this')
group.add_argument('--nproc', '-n', type=int, default=1,
                   help='number of process used in fitting baseline')
group = parser.add_argument_group('preprocessing before baseline fitting')
group.add_argument('-T', '--trans', type=bool_fun, choices=[True, False], default='False',
                   help='')
group.add_argument('--njoin', type=int, default=0,
                   help='join spectra (average) to fit same baseline')
group.add_argument('--s_method_t', default='none', choices=['none', 'gaussian', 'boxcar', 'median'],
                   help='method used to smooth every channel along time axis')
group.add_argument('--s_sigma_t', type=int, default=5,
                   help='used with --s_method_t')
group.add_argument('--s_method_freq', default='none', choices=['none', 'median', 'gaussian', 'boxcar', 'PLS', 'fft'],
                   help='method used to smooth every spectrum along frequency axis')
group.add_argument('--s_sigma_freq', type=float, default=5,
                   help='used with --s_method_freq')
group.add_argument('--average_every_freq', type=int, default=0,
                   help='')
group = parser.add_argument_group('fit and subtract the baseline')
group.add_argument('--lam', type=float, default=1.0e8,
                   help='baseline fit parameters')
group.add_argument('--deg', type=int, default=2,
                   help='baseline fit parameters')
group.add_argument('--offset', type=float, default=2,
                   help='baseline fit parameters')
group.add_argument('--ratio', type=float, default=0.01,
                   help='baseline fit parameters')
group.add_argument('--niter', type=int, default=100,
                   help='baseline fit parameters')
group.add_argument('--exclude_type',
                   help='baseline fit parameters')

# interaction
group = parser.add_argument_group(f'*Interaction\n{sep_line}')
group.add_argument('-i', '--interact', action='store_true', not_in_write_out_config_file=True,
                   help='interaction')
group.add_argument('--ylim', nargs='+', default=['auto'], not_in_write_out_config_file=True,
                   help='ylim')
group.add_argument('--figsize', type=float, nargs=2, default=(10, 7), not_in_write_out_config_file=True,
                   help='figsize')
group.add_argument('--length', type=int, default=20, not_in_write_out_config_file=True,
                   help='spetra numbers used to test')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        return '-bld'

    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global h5py, OrderedDict, sub_baseline

        import h5py
        from collections import OrderedDict
        from .core.baseline import sub_baseline

    @staticmethod
    def fit_baseline(s2p, freq, mjd, args, is_excluded=None):
        fit_kwargs = {}
        keys = ['method', 'nproc',
                'njoin', 's_method_t', 's_sigma_t', 's_method_freq', 's_sigma_freq',
                'lam', 'deg', 'offset', 'ratio', 'niter', 'exclude_type']
        for key in keys:
            fit_kwargs[key] = getattr(args, key)
        fit_kwargs['verbose'] = args.show_prog
        fit_kwargs['is_excluded'] = is_excluded
        if args.trans:
            return sub_baseline(mjd, s2p.transpose((1, 0, 2)), subtract=True, **fit_kwargs).transpose((1, 0, 2))
        else:
            return sub_baseline(freq, s2p, subtract=True, **fit_kwargs)

    def _load_is_excluded(self,):
        import numpy as np
        fs = self.fs
        if 'is_excluded' in fs.keys():
            is_excluded = fs['is_excluded'][:]
            if is_excluded.ndim != self.s2p.ndim:
                is_excluded = np.full(is_excluded.shape + (2,), is_excluded[...,None])
            self.is_excluded = is_excluded

    def gen_s2p_out(self,):
        args = self.args
        # gen self.s2p_out
        s2p = self.s2p[:]
        # is_excluded
        self._load_is_excluded()
        # fit baseline:
        if args.method is not None and args.method != 'none':
            print('fit and substract baseline')
            s2p = self.fit_baseline(s2p, self.freq, self.mjd, args, getattr(self, 'is_excluded', None))
        else:
            print('no baseline method assigned, skip. Make sure the input spectra have been baselined.')
        self.s2p_out = s2p

# Internal Cell
def check_backend():
    import matplotlib as mpl
    if 'ipympl' not in mpl.get_backend():
        print('Please use interaction mode in Jupyert and run \'%matplotlib ipympl\' in the notebook cell first')
        sys.exit()


def interact(args):
    check_backend()
    import h5py
    from .interaction import bld_i as interact
    f = h5py.File(args.fpath, 'r')
    fs = f['S']
    if 'T' in fs.keys():
        T = fs['T']
    elif 'Ta' in fs.keys():
        T = fs['Ta']
    elif 'flux' in fs.keys():
        T = fs['flux']
    if 'is_excluded' in fs.keys():
        is_excluded = fs['is_excluded']
    else:
        is_excluded = None
    interact.T2p = T
    interact.is_excluded = is_excluded
    interact.freq = fs['freq'][:]
    interact.frange = args.frange
    interact.nproc = args.nproc
    interact.length = args.length
    interact.figsize = args.figsize
    interact.ylim = args.ylim[0] if len(args.ylim) == 1 else args.ylim
    interact.main()
    # sys.exit()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()

    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    if args_.interact:
        interact(args_)
    else:
        print('#'*35+'Args'+'#'*35)
        print(parser.format_values())  # useful for logging where different settings came from
        print('#'*35+'####'+'#'*35)
        io = IO(args_)
        io()
