# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S2-bld.ipynb (unless otherwise specified).

__all__ = ['IO', 'IO_i']

# Cell
import numpy as np
from .utils.io import *

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract the baseline',)
add_common_argument(parser)
parser.add_argument('fpath',
                    help='Path to the input file containing spectra data with temperature or flux.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Specify the frequency range to limit the analysis to. Expects two float values: start and end frequencies.')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="If enabled, skips the verification or addition of right ascension (RA) and declination (Dec) information.")
parser.add_argument('--show_prog', type=bool_fun, choices=[True, False], default='True', env_var='HIFAST_SHOW_PROG',
                    help='Set to True to display progress during the fitting of spectra; otherwise set to False.')

parser.add_argument('--nproc', '-n', type=int, default=1,
                   help='Specifies the number of processes to use during baseline fitting.')
# baseline fitting
group = parser.add_argument_group(f'*BaseLine fitting {sep_line}')

rew_type = ['asym1', 'asym2', 'asym3', 'sym1',]
method = ['none']
method += ['PLS-'+r for r in rew_type]
method += ['poly-'+r for r in rew_type]
method += ['knpoly-'+r for r in rew_type]
method += ['Gauss-'+r for r in rew_type]
method += ['knspline-'+r for r in rew_type]
method += ['masPLS-'+r for r in rew_type]
method += ['asPLS', 'arPLS']
method += ['original']

group.add_argument('--method', default='arPLS', choices=method,
                   help='Select the baseline fitting method to use from the available options.')
group = parser.add_argument_group('preprocessing before baseline fitting')
group.add_argument('-T', '--trans', type=bool_fun, choices=[True, False], default='False',
                   help='Set to True to fit the baseline along the time axis instead of the frequency axis.\
                    The parameters `--njoin_t` and `--njoin_freq`, `--s_method_t` and `--s_method_freq`, along with  `--s_sigma_t` and `--s_sigma_freq`, are correspondingly interchanged.\
                    The parameters for post low-order polynomial fitting are similarly exchanged.')
group.add_argument('--njoin', '--njoin_t', type=int, default=0,
                   help='Combine (average) a specified number of spectra to fit a common baseline.')
group.add_argument('--s_method_t', default='none', choices=['none', 'gaussian', 'boxcar', 'median'],
                   help='Choose the smoothing method to apply to each channel along the time axis.')
group.add_argument('--s_sigma_t', type=int, default=5,
                   help='Used with `--s_method_t`. Standard deviation of Gaussian smoothing or 2*`s_sigma_t`+1 for boxcar/median smoothing window width.')
group.add_argument('--s_method_freq', default='none', choices=['none', 'gaussian', 'boxcar', 'median', 'PLS', 'fft'],
                   help='Select the smoothing method to apply to each spectrum along the frequency axis.')
group.add_argument('--s_sigma_freq', type=float, default=5,
                   help='Used with `--s_method_freq`. Standard deviation of Gaussian smoothing or 2*`s_sigma_t`+1 for boxcar/median smoothing window width.')
group.add_argument('--average_every_freq', '--njoin_freq', type=int, default=0,
                   help='Factor by which to bin (average) the channels along the frequency axis.')

group = parser.add_argument_group('fit and subtract the baseline')
group.add_argument('--lam', type=float, default=1.0e8,
                   help='Set the smoothing parameter for `*PLS` methods. Larger values result in a baseline closer to a low-order polynomial. Adjust using a logarithmic scale.')
group.add_argument('--deg', type=int, default=2,
                   help='Specify the polynomial degree for `poly-*` methods.')
group.add_argument('--knots', type=str,
                   help='Path to a JSON file containing predefined knots for `knspline-*` methods.')
group.add_argument('--offset', type=float, default=2,
                   help='Offset parameter for baseline fitting.')
group.add_argument('--ratio', type=float, default=0.01,
                   help='Ratio parameter for baseline fitting.')
group.add_argument('--niter', type=int, default=100,
                   help='Maximum number of iterations for baseline fitting.')
group.add_argument('--exclude_add', '--exclude_type', default='none', choices=['none', 'auto1', 'auto2'],
                   help='Additional exclusion parameters for baseline fitting.')

group = parser.add_argument_group(f'Use pre-determined is_excluded array in input file\n{sep_line}')
group.add_argument('--use_pre_is_excluded', type=bool_fun, choices=[True, False], default='False',
                   help='Use a pre-determined is_excluded array from the input file to mask channels, if available.')
# Exclude files
group = parser.add_argument_group(f'Exclude known source catalogs\n{sep_line}')
group.add_argument('--src_file',
                   help='Path to a text catalog with columns for RA [deg], Dec [deg], radius [arcmin], minimum frequency [MHz], and maximum frequency [MHz]. Identified sources will be added to the is_excluded array.')
group.add_argument('--frame', choices=['BARYCENT', 'HELIOCEN', 'LSRK', 'LSRD'], default='LSRK',
                   help='Specify the velocity rest frame for excluding source frequency ranges.')

# low-order polynomial on individual spectrum
group = parser.add_argument_group(f'*Post-applying low-order polynomial fitting on *individual* spectrum if `--s_method_t` or `--njoin` used [optional]\n{sep_line}')

rew_type = ['asym1', 'asym2', 'asym3', 'sym1',]
method = ['none']
method += ['poly-'+r for r in rew_type]

group.add_argument('--post_method', default='none', choices=method,
                   help='Select the method for post-application baseline fitting.')
group.add_argument('--post_s_method_freq', default='none', choices=['none', 'gaussian', 'boxcar', 'median', 'PLS', 'fft'],
                   help='Smoothing method for each spectrum along the frequency axis after baseline subtraction.')
group.add_argument('--post_s_sigma_freq', type=float, default=5,
                   help='Standard deviation for Gaussian smoothing along the frequency axis after baseline subtraction.')
group.add_argument('--post_average_every_freq', type=int, default=0,
                   help='Bin the channels by this factor after baseline subtraction.')
group.add_argument('--post_deg', type=int, default=2,
                   help='Polynomial degree for `*-poly` methods used after baseline subtraction.')
group.add_argument('--post_offset', type=float, default=2,
                   help='Offset parameter for baseline fitting after baseline subtraction.')
group.add_argument('--post_ratio', type=float, default=0.01,
                   help='Ratio parameter for baseline fitting after baseline subtraction.')
group.add_argument('--post_niter', type=int, default=100,
                   help='Number of iterations for baseline fitting after baseline subtraction.')
group.add_argument('--post_exclude_add', '--post_exclude_type', default='none', choices=['none', 'auto1', 'auto2'],
                   help='Additional exclusion parameters for baseline fitting after baseline subtraction.')
# interaction
group = parser.add_argument_group(f'*Interaction\n{sep_line}')
group.add_argument('-i', '--interact', action='store_true', not_in_write_out_config_file=True,
                   help='Enable interactive mode for additional manual control and visualization.')
group.add_argument('--ylim', nargs='+', default=['auto'], not_in_write_out_config_file=True,
                   help='Set the y-axis limits for the plots. Use "auto" for automatic scaling or provide two float values for the lower and upper limits.')
group.add_argument('--figsize', type=float, nargs=2, default=(10, 7), not_in_write_out_config_file=True,
                   help='Specify the figure size for plots as a tuple of width and height in inches.')
group.add_argument('--length', type=int, default=20, not_in_write_out_config_file=True,
                   help='Number of spectra to use for testing purposes.')
group.add_argument('--start_init', type=int, default=0, not_in_write_out_config_file=True,
                   help='Index of the first spectrum to display when starting the program.')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        fpart = '-bld'
        if self.args.post_method is not None and self.args.post_method != 'none':
            fpart += '_p'
        return fpart

    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global h5py, OrderedDict, sub_baseline

        import h5py
        from collections import OrderedDict
        from .core.baseline import sub_baseline

    @staticmethod
    def fit_baseline(s2p, freq, mjd, args, is_excluded=None):
        fit_kwargs = {}
        keys = ['nproc',
                'method',
                'njoin',
                's_method_t',
                's_sigma_t',
                's_method_freq',
                's_sigma_freq',
                'average_every_freq',
                'lam',
                'deg',
                'offset',
                'ratio',
                'niter',
                'exclude_add',
               ]
        for key in keys:
            fit_kwargs[key] = getattr(args, key)
        fit_kwargs['is_excluded'] = is_excluded

        if fit_kwargs['method'].startswith('knspline') or fit_kwargs['method'].startswith('knpoly'):
            # load knots from knots file
            import json
            with open(args.knots, 'r') as f:
                fit_kwargs['knots'] = json.load(f)

        trans = getattr(args, 'trans', False)
        if trans:
            if fit_kwargs['is_excluded'] is not None:
                 fit_kwargs['is_excluded'] = fit_kwargs['is_excluded'].transpose((1, 0, 2))
            return sub_baseline(np.arange(len(mjd)), s2p.transpose((1, 0, 2)), subtract=True, **fit_kwargs).transpose((1, 0, 2))
        else:
            return sub_baseline(freq, s2p, subtract=True, **fit_kwargs)

    @staticmethod
    def post_fit_baseline(s2p, freq, mjd, args, is_excluded=None):
        fit_kwargs = {}
        keys = ['method',
                's_method_freq',
                's_sigma_freq',
                'average_every_freq',
                'deg',
                'offset',
                'ratio',
                'niter',
                'exclude_add',
               ]
        for key in keys:
            fit_kwargs[key] = getattr(args, 'post_'+key)
        fit_kwargs['nproc'] = args.nproc
        fit_kwargs['njoin'] = 0
        fit_kwargs['s_method_t'] = 'none'
        fit_kwargs['s_sigma_t'] = 0
        fit_kwargs['lam'] = 0
        fit_kwargs['is_excluded'] = is_excluded

        trans = getattr(args, 'trans', False)
        if trans:
            if fit_kwargs['is_excluded'] is not None:
                 fit_kwargs['is_excluded'] = fit_kwargs['is_excluded'].transpose((1, 0, 2))
            return sub_baseline(np.arange(len(mjd)), s2p.transpose((1, 0, 2)), subtract=True, **fit_kwargs).transpose((1, 0, 2))

        return sub_baseline(freq, s2p, subtract=True, **fit_kwargs)

    def _load_is_rfi(self,):
        fs = self.fs
        if 'is_rfi' in fs.keys():
            is_rfi = fs['is_rfi'][:]
            if self.is_use_freq is not None:
                is_rfi = is_rfi[:, self.is_use_freq]

                # M06 bandpass is not flat in [1410, 1416]
            if self.nB == 6:
                whole_rfi = np.all(is_rfi, axis=1)
                freq = self.freq
                is_use = (freq > 1406) & (freq < 1416)
                is_rfi[:, is_use] = False
                is_rfi[whole_rfi] = True

            self.is_rfi = is_rfi

    def _load_is_excluded(self):
        if not self.args.use_pre_is_excluded:
            return
        fs = self.fs
        if 'is_excluded' in fs.keys():
            is_excluded = fs['is_excluded'][:]
            if self.is_use_freq is not None:
                is_excluded = is_excluded[:, self.is_use_freq]
            # M06 bandpass is not flat in [1410, 1416]
            if self.nB == 6:
                freq = self.freq
                is_use = (freq > 1406) & (freq < 1416)
                is_excluded[:, is_use] = False
            self.is_excluded = is_excluded

    def _load_sources(self):
        args = self.args
        fpath = args.src_file
        if fpath is not None:
            from .core.regions import mask_srcs
            is_excluded = self.is_excluded if hasattr(self,'is_excluded') else np.zeros(self.s2p.shape[:2], dtype = bool)
            print(f"loading excluded files from {fpath}")
            self.is_excluded = mask_srcs(fpath, is_excluded, self.ra, self.dec, self.freq,
                                         self.mjd, inplace=True, rest_frame=args.frame)

    def gen_s2p_out(self,):
        args = self.args

        # gen self.s2p_out
        s2p = self.s2p[:]
        # rfi not in is_excluded
        self._load_is_rfi()
        # is_excluded
        self._load_is_excluded()
        # src add to is_excluded
        self._load_sources()

        # fit baseline:
        if args.method is not None and args.method != 'none':
            if hasattr(self,'is_excluded'):
                is_excluded = self.is_excluded
                # suppress nan warning in baseline fitting in the future
                # whole_rfi = np.all(is_excluded, axis=1)
                # is_excluded[whole_rfi] = False # I don't like some warnings when whole spec is nan ...
                # check is_excluded shape
                if is_excluded.ndim == 2:
                    is_excluded = np.full(is_excluded.shape + s2p.shape[2:], is_excluded[..., None])
                else:
                    raise(ValueError('Now `is_excluded` only supports 2-dim.'))
            else:
                is_excluded = None

            print('fit and substract baseline')
            s2p = self.fit_baseline(s2p, self.freq, self.mjd, args, is_excluded)
            if args.post_method is not None and args.post_method !='none':
                print('applying low-order polynomial fitting on each spectrum')
                s2p = self.post_fit_baseline(s2p, self.freq, self.mjd, args, is_excluded)
        else:
            print('no baseline method assigned, skip. Make sure the input spectra have been baselined.')
        self.s2p_out = s2p

    def __call__(self, save=True):
        self.gen_s2p_out()
        self.gen_dict_out()

        if hasattr(self, 'is_excluded'):
            # update
            self.dict_out['is_excluded'] = self.is_excluded
        if hasattr(self, 'is_rfi'):
            # update
            self.dict_out['is_rfi'] = self.is_rfi

        # save to hdf5 file
        if save:
            self.save()

# Internal Cell
def check_backend():
    import matplotlib as mpl
    if 'ipympl' not in mpl.get_backend():
        print('Please use interaction mode in Jupyert and run \'%matplotlib ipympl\' in the notebook cell first')
        sys.exit()

interact_save_lim = 20
def interact(args):
    check_backend()
    import h5py
    from .interaction import bld_i as interact
    f = h5py.File(args.fpath, 'r')
    fs = f['S']
    if 'T' in fs.keys():
        T = fs['T']
    elif 'Ta' in fs.keys():
        T = fs['Ta']
    elif 'flux' in fs.keys():
        T = fs['flux']
    if args.use_pre_is_excluded and 'is_excluded' in fs.keys():
        is_excluded = fs['is_excluded']
    else:
        is_excluded = None
    interact.T2p = T
    interact.is_excluded = is_excluded
    interact.freq = fs['freq'][:]
    interact.frange = args.frange
    interact.nproc = args.nproc
    interact.length = min(args.length, interact.T2p.shape[1])
    interact.figsize = args.figsize
    interact.ylim = args.ylim[0] if len(args.ylim) == 1 else args.ylim
    interact.trans = args.trans
    interact.start_init = args.start_init
    if T.shape[1] <= interact_save_lim:
        interact.save = True
    else:
        interact.save = False
    return interact.main()
    # sys.exit()

# Cell
class IO_i(IO):

    def set_interact_spec(self, interact_spec):
        self.interact_spec = interact_spec

    def gen_s2p_out(self,):
        args = self.args
        if args.interact:
            print('Please ensure you have adjusted the parameters for each `polar`, otherwise you will get nan vaules in the file')
            self.s2p_out = self.interact_spec.bld_out
            return

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    if args_.interact:
        interact_spec, widgets = interact(args_)[0:2]
        save = IO_i(args_, HistoryAdd={'interact':str(widgets)})
        save.set_interact_spec(interact_spec)
        if interact_spec.save:
            print('Please run \'save()\' in the notebook cell to save your results')
    else:
        print('#'*35+'Args'+'#'*35)
        args_from = parser.format_values()
        print(args_from)
        print('#'*35+'####'+'#'*35)

        HistoryAdd = {'args_from': args_from} if args_.my_config is not None else None
        io = IO(args_, HistoryAdd=HistoryAdd)
        io()
