# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S2-bld.ipynb (unless otherwise specified).

__all__ = ['sep_line', 'parser', 'group', 'group', 'group', 'group']

# Cell
from .utils.io import *

# Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract baseline', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature or flux file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")

# group = parser.add_argument_group(f'*Flux\n{sep_line}')
# group.add_argument('--flux', type=bool_fun, choices=[True, False], default='False',
#                    help='if True, convert  the temperature to flux before subtract baseline')
# group.add_argument('--cali_fname', default='none',
#                    help='quasar calibration file name')

# baseline fitting
group = parser.add_argument_group(f'*BaseLine (set --method as none to skip this) \n{sep_line}')
group.add_argument('--method', default='arPLS', choices=['none', 'arPLS', 'srPLS', 'Chebyshev', 'poly', 'original', ],
                   help='method used to fit baseline, if set as none, skip this')
group.add_argument('--nproc', '-n', type=int, default=1,
                   help='number of process used in fitting baseline')
group = parser.add_argument_group('preprocessing before baseline fitting')
group.add_argument('-T', '--trans', type=bool_fun, choices=[True, False], default='False',
                   help='')
group.add_argument('--njoin', type=int, default=0,
                   help='join spectra (average) to fit same baseline')
group.add_argument('--s_method_t', default='none', choices=['none', 'gaussian', 'boxcar', 'median'],
                   help='method used to smooth every channel along time axis')
group.add_argument('--s_sigma_t', type=int, default=5,
                   help='used with --s_method_t')
group.add_argument('--s_method_freq', default='none', choices=['none', 'median', 'gaussian', 'boxcar', 'PLS', 'fft'],
                   help='method used to smooth every spectrum along frequency axis')
group.add_argument('--s_sigma_freq', type=float, default=5,
                   help='used with --s_method_freq')
group.add_argument('--average_every_freq', type=int, default=0,
                   help='')
group = parser.add_argument_group('fit and subtract the baseline')
group.add_argument('--lam', type=float, default=1.0e8,
                   help='baseline fit parameters')
group.add_argument('--deg', type=int, default=2,
                   help='baseline fit parameters')
group.add_argument('--offset', type=float, default=2,
                   help='baseline fit parameters')
group.add_argument('--ratio', type=float, default=0.01,
                   help='baseline fit parameters')
group.add_argument('--niter', type=int, default=100,
                   help='baseline fit parameters')

# interaction
group = parser.add_argument_group(f'*Interaction\n{sep_line}')
group.add_argument('-i', '--interact', action='store_true', not_in_write_out_config_file=True,
                   help='interaction')
group.add_argument('--ylim', nargs='+', default=['auto'], not_in_write_out_config_file=True,
                   help='ylim')
group.add_argument('--figsize', type=float, nargs=2, default=(10, 7), not_in_write_out_config_file=True,
                   help='figsize')
group.add_argument('--length', type=int, nargs=1, default=20, not_in_write_out_config_file=True,
                   help='spetra numbers used to test')

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    io = IO(args_)
    io()