# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/E-convert.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .utils.io import *

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract baseline', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature or flux file path.')

# Internal Cell
if __name__ == '__main__':
    args = parser.parse_args()
    dict_in = load_hdf5_to_dict_old(args.fpath)

    if 'T' in dict_in.keys():
        wcs_data_name = 'T'
    elif 'Ta' in dict_in.keys():
        wcs_data_name = 'Ta'
    elif 'flux' in dict_in.keys():
        wcs_data_name = 'flux'
    else:
        raise(ValueError('can not find spec'))

    dict_in[wcs_data_name] = MjdChanPolar_to_PolarMjdChan(dict_in[wcs_data_name])

    save_specs_hdf5(os.path.join(args.outdir, os.path.basename(args.fpath)), dict_in)