# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cross_match.ipynb (unless otherwise specified).

__all__ = ['CrossMatch', 'CrossMatch']

# Cell
import numpy as np
import matplotlib.pyplot as plt
import h5py

from astropy import units as u
from astropy.coordinates import SkyCoord

import sys

# Cell
class CrossMatch(object):
    def __init__(self, ra1, dec1, ra2, dec2, sep=5):
        """
        ra dec : deg
        sep : arcsec
        """
        c1 = SkyCoord(ra=ra1*u.degree, dec=dec1*u.degree, frame='icrs')
        c2 = SkyCoord(ra=ra2*u.degree, dec=dec2*u.degree, frame='icrs')
        ind_inc2, seps, _, = c1.match_to_catalog_sky(c2)
        is_match = seps < sep*u.arcsec
        self.inds_1 = np.where(is_match)[0]
        self.inds_2 = ind_inc2[is_match]

    def select_match(self, x1, yss1, x2, yss2, xrange):
        is_use = (x1 > xrange[0]) & (x1 < xrange[1])
        self.x1_u = x1[is_use]
        self.yss1_u = yss1[self.inds_1][:, is_use]
        is_use = (x2 > xrange[0]) & (x2 < xrange[1])
        self.x2_u = x2[is_use]
        self.yss2_u = yss2[:][self.inds_2][:, is_use]

    def get_ratio(self,):
        return np.median(np.median(self.yss1_u/self.yss2_u, axis=1))

# Cell
if __name__ == '__main__':
    import h5py
    import argparse
    import os
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument('fname1',
                        help='base file name')
    parser.add_argument('fname2',
                        help='reference file name')
#     parser.add_argument('-f', '--force', action='store_true',
#                         help='overwriting file if out file exists')
    parser.add_argument('--outdir',
                        help='default is same with the input file')
    args = parser.parse_args()
    fname1, fname2 = args.fname1, args.fname2
    # open file
    f1 = h5py.File(args.fname1, 'r')
    f2 = h5py.File(args.fname2, 'r')
    # load
    ra1 = f1['ra'][:]
    dec1 = f1['dec'][:]
    ra2 = f2['ra'][:]
    dec2 = f2['dec'][:]
    vel1 = f1['vel'][:]
    vel2 = f2['vel'][:]
    #freq1 = f1['freq'][:]
    #freq2 = f2['freq'][:]

    key = 'flux'
    # para
    sep = 8  # arcsec
    xrange = [-15, 15]

    CM = CrossMatch(ra1, dec1, ra2, dec2, sep)
    CM.select_match(vel1, f1[key], vel2, f2[key], xrange)
    CM.get_ratio()

    # out dict
    dict_out = {}
    for _key in f1.keys():
        if _key not in ['Header', key]:
            dict_out[_key] = f1[_key][:]
    dict_out[key] = (f1[key][:]/CM.get_ratio()).astype('float32')

    # save file
    print('Saving...')
    from .utils.io import add_extra, rec_his, save_dict_hdf5
    add_extra(f1, dict_out)
    if 'Header' in f1.keys():
        from collections import OrderedDict
        header_in = OrderedDict(f1['Header'].attrs.items())
    else:
        header_in = None
    f1.close()
    header = rec_his(args=args)
    if header_in is not None:
        header.update(header_in)
    outpart = '-cm'
    if args.outdir is None:
        args.outdir = os.path.dirname(fname1)
    fileout = os.path.join(args.outdir, '.'.join(os.path.basename(fname1).split('.')[:-1]) + f'{outpart}.hdf5')
    save_dict_hdf5(fileout, dict_out, header=header)
    print(f"Saved to {fileout}")

# Cell
import numpy as np
import matplotlib.pyplot as plt
import h5py

from astropy import units as u
from astropy.coordinates import SkyCoord

import sys

# Cell
class CrossMatch(object):
    def __init__(self, ra1, dec1, ra2, dec2, sep=5):
        """
        ra dec : deg
        sep : arcsec
        """
        c1 = SkyCoord(ra=ra1*u.degree, dec=dec1*u.degree, frame='icrs')
        c2 = SkyCoord(ra=ra2*u.degree, dec=dec2*u.degree, frame='icrs')
        ind_inc2, seps, _, = c1.match_to_catalog_sky(c2)
        is_match = seps < sep*u.arcsec
        self.inds_1 = np.where(is_match)[0]
        self.inds_2 = ind_inc2[is_match]

    def select_match(self, x1, yss1, x2, yss2, xrange):
        is_use = (x1 > xrange[0]) & (x1 < xrange[1])
        self.x1_u = x1[is_use]
        self.yss1_u = yss1[self.inds_1][:, is_use]
        is_use = (x2 > xrange[0]) & (x2 < xrange[1])
        self.x2_u = x2[is_use]
        self.yss2_u = yss2[:][self.inds_2][:, is_use]

    def get_ratio(self,):
        return np.median(np.median(self.yss1_u/self.yss2_u, axis=1))

# Cell
if __name__ == '__main__':
    import h5py
    import argparse
    import os
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument('fname1',
                        help='base file name')
    parser.add_argument('fname2',
                        help='reference file name')
#     parser.add_argument('-f', '--force', action='store_true',
#                         help='overwriting file if out file exists')
    parser.add_argument('--outdir',
                        help='default is same with the input file')
    args = parser.parse_args()
    fname1, fname2 = args.fname1, args.fname2
    # open file
    f1 = h5py.File(args.fname1, 'r')
    f2 = h5py.File(args.fname2, 'r')
    # load
    ra1 = f1['ra'][:]
    dec1 = f1['dec'][:]
    ra2 = f2['ra'][:]
    dec2 = f2['dec'][:]
    vel1 = f1['vel'][:]
    vel2 = f2['vel'][:]
    #freq1 = f1['freq'][:]
    #freq2 = f2['freq'][:]

    key = 'flux'
    # para
    sep = 8  # arcsec
    xrange = [-15, 15]

    CM = CrossMatch(ra1, dec1, ra2, dec2, sep)
    CM.select_match(vel1, f1[key], vel2, f2[key], xrange)
    CM.get_ratio()

    # out dict
    dict_out = {}
    for _key in f1.keys():
        if _key not in ['Header', key]:
            dict_out[_key] = f1[_key][:]
    dict_out[key] = (f1[key][:]/CM.get_ratio()).astype('float32')

    # save file
    print('Saving...')
    from .utils.io import add_extra, rec_his, save_dict_hdf5
    add_extra(f1, dict_out)
    if 'Header' in f1.keys():
        from collections import OrderedDict
        header_in = OrderedDict(f1['Header'].attrs.items())
    else:
        header_in = None
    f1.close()
    header = rec_his(args=args)
    if header_in is not None:
        header.update(header_in)
    outpart = '-cm'
    if args.outdir is None:
        args.outdir = os.path.dirname(fname1)
    fileout = os.path.join(args.outdir, '.'.join(os.path.basename(fname1).split('.')[:-1]) + f'{outpart}.hdf5')
    save_dict_hdf5(fileout, dict_out, header=header)
    print(f"Saved to {fileout}")