# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cube.ipynb (unless otherwise specified).

__all__ = ['sep_line', 'parser']

# Cell
from .utils.io import *

# Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='imaging cube data', )


parser.add_argument('fpatterns', nargs='+',
                    help='file names or file pattern')
parser.add_argument('--outname', required=True,
                   help='output file name, full path')
parser.add_argument('-f', action='store_true', dest='force',
                    help='if set, overwriting file if output file exists')

parser.add_argument('--nproc', '-n', type=int, default=1,
                   help='number of process used ')
parser.add_argument('--step', type=int, default=5,
                   help='file number used to gridding each once')
parser.add_argument('--share_mem', type=bool_fun, choices=[True, False], default='False',
                   help='May reduce the memory usage when nproc > 1, or may not. Only in Linux')

parser.add_argument('--ra_range', type=float, nargs=2,
                   help='ra range; unit: deg')
parser.add_argument('--dec_range', type=float, nargs=2,
                   help='dec_range; unit: deg')

parser.add_argument('--wcs_ra_center', type=float,
                   help='unit: deg')
parser.add_argument('--wcs_dec_center', type=float,
                   help='unit: deg')

parser.add_argument('--range3', type=float, nargs=2,
                   help='freq or vel range')
parser.add_argument('--type3', choices=['vopt', 'vrad', 'freq'], default='vrad',
                   help='third axis in cube,  ``vopt, ``vrad`` or ``freq``')

parser.add_argument('--bwidth', type=float, default=[60.],nargs='+',
                   help='unit: arc second')
parser.add_argument('-p', '--proj', default='AIT', #choices=['AIT', 'SIN', 'TAN'],
                   help='wcs projection. See arXiv:astro-ph/0207413, Section 7.2. Choice of projection')
parser.add_argument('-k', '--key', choices=['flux', 'Ta'],
                       help='')

parser.add_argument('-m', '--method', default='gaussian', choices=['gaussian', 'bessel_gaussian', 'sinc_gaussian'],
                   help='method to process the spec in r_cut')

parser.add_argument('--beam_fwhw', type=float, default=2.9,
                   help='beam Full width at half maximum; unit: arc minute')
parser.add_argument('--gaussian_fwhw', type=float,
                   help='unit: arc minute; default: ``beam_fwhw/2``')
parser.add_argument('--bsize', type=float,
                   help='for Bessel in bessel_gaussian or sin in sinc_gaussian; unit: arc minute'+
                        '; default: ``1.55*beam_fwhw/3``')
parser.add_argument('--gsize', type=float,
                   help='for gauss in bessel_gaussian or sinc_gaussian; unit: arc minute' +
                        '; default: ``2.52*beam_fwhw/3``')

parser.add_argument('--r_cut', type=float,
                   help="spectra inside r_cut from the grid point will be considered; unit: arc second. \n" +
                        "Default: \n"+
                        "``--method gaussian``: 3*gaussian_sigma, i.e. 3*(gaussian_fwhw/(sqrt(8ln(2))));\n" +
                        "``--method bessel_gaussian``: 3.8317059702075*bsize/pi;\n"+
                        "``--method sinc_gaussian``: bsize")

parser.add_argument('--frac_finite_min', type=float, default=1,
                   help='For a grid point having ``n``` spectra in ``r_cut``, if the number of ``finite value``  in a channel is zero ' +
                        'or smaller than ``frac_finite_min*n``, the output value in the channel will be set as ``nan``')

parser.add_argument('--polar', choices=['XX','YY','M'], default='M',
                       help='polarization')

parser.add_argument('--wcs_from',
                   help='use the wcs parameters from input fits')

parser.add_argument('--scale_beams_file',
                   help='testing')

# Cell
if __name__ == '__main__':
    import os
    from .core.image import Imaging
    args_ = parser.parse_args()

    # disable using storage disk in Multiprocessing.Array
    # https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir
    # https://docs.python.org/3/library/tempfile.html#tempfile.tempdir
    # os.environ['TMPDIR'] = '/dev/shm'
    if sys.platform == 'linux' and args_.share_mem:
        import tempfile
        tempfile.tempdir = '/dev/shm'

    img = Imaging(args_)
    img()
