# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S1-flux.ipynb (unless otherwise specified).

__all__ = ['parser', 'IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='Convert the spectra temperature to flux', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="if set, don't check or add ra dec")
group = parser.add_argument_group(f'*Flux\n{sep_line}')
# --flux affect the outfield name
group.add_argument('--flux', type=bool_fun, choices=[True], default='True', not_in_write_out_config_file=True,
                   help='It must be True.')
group.add_argument('--cali_fname', default='none',
                   help='calibration source file name')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-flux'
        return fpart

    def gen_s2p_out(self,):
        args = self.args
        s2p = self.s2p[:]
        from .core.flux import cali_src
        print('Flux calibrating ...')
        self.s2p_out = cali_src(s2p, self.nB, self.freq, args.cali_fname, ra=self.ra, dec=self.dec, mjd=self.mjd)

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    print(parser.format_values())  # useful for logging where different settings came from
    print('#'*35+'####'+'#'*35)
    io = IO(args_)
    io()