# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S1-flux.ipynb (unless otherwise specified).

__all__ = ['IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='Convert the spectra temperature to flux', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="if set, don't check or add ra dec")
group = parser.add_argument_group(f'*Flux\n{sep_line}')
# --flux affect the outfield name
group.add_argument('--flux', type=bool_fun, choices=[True], default='True', not_in_write_out_config_file=True,
                   help='It must be True.')
group.add_argument('--cali_fname', default='none',
                   help='calibration source file name')
group.add_argument('--fix_diff_tcal', type=bool_fun, choices=[True, False], default='True',
                   help='If True, fix the tcal differece in spec and calibator')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-flux'
        return fpart

    def gen_s2p_out(self,):
        args = self.args
        s2p = self.s2p[:]
        from .core.flux import cali_src
        print('Flux calibrating ...')
        if args.fix_diff_tcal:
            tcal_spec = self.fs['Tcal'][:]
            if self.is_use_freq is not None:
                tcal_spec = tcal_spec[:, self.is_use_freq]
        else:
            tcal_spec = None
        if args.cali_fname != 'none' and args.cali_fname is not None:
            print(f'using {args.cali_fname} ...')
        self.s2p_out = cali_src(s2p, self.nB, self.freq, args.cali_fname, ra=self.ra, dec=self.dec, mjd=self.mjd,
                               tcal_spec=tcal_spec)

# Cell
if __name__ == '__main__':
    dests_hide = ['flux',]
    hide_paras(parser, dests_hide)

    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    args_from = parser.format_values()
    args_from = del_paras_in_string(args_from, dests_hide)
    print(args_from)
    print('#'*35+'####'+'#'*35)

    HistoryAdd = {'args_from': args_from} if args_.my_config is not None else None
    io = IO(args_, HistoryAdd=HistoryAdd)
    io()
