# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S5-multi.ipynb (unless otherwise specified).

__all__ = ['IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='reference frame correction and etc.', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
group = parser.add_argument_group(f'*frame correction\n{sep_line}')
# frame correct
group.add_argument('--fc', type=bool_fun, choices=[True, False], default='True', not_in_write_out_config_file=True,
                   help='frame correct')
group.add_argument('--frame', choices=['HELIOCEN', 'LSRK'], default='LSRK',
                   help='Velocity Rest Frames, HELIOCEN or LSRK')
group = parser.add_argument_group(f'*after\n{sep_line}')
group.add_argument('--replace_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='if True, replace spectra contaminated by rfi as np.nan')
group.add_argument('--merge_polar', type=bool_fun, choices=[True, False], default='True',
                   help='if True, average two polarization')

# Cell
class IO(BaseIO):
    ver = 'old'
    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-fc'
        return fpart

    def __call__(self, save=True):
        import numpy as np
        args = self.args
        s2p = self.s2p[:]
        # try load is_rfi
        if 'is_rfi' in self.fs.keys():
                # if not replace_rfi, frame correct it

                if self.is_use_freq is not None:
                    inds = np.where(self.is_use_freq)[0]
                    is_rfi = self.fs['is_rfi'][:, inds]
                else:
                    is_rfi = self.fs['is_rfi'][:]
                if args.replace_rfi:
                    print('replacing RFI')
                    s2p[is_rfi] = np.nan
        else:
            is_rfi = None

        if args.merge_polar and s2p.ndim == 3:
            print('average two polarization...')
            s2p = np.mean(s2p, axis=2, keepdims=True)
        # frame
        if args.fc:
            from .core.corr_vel import freq2vel, frame_correct
            if 'frame' in self.Header.keys():
                raise(ValueError(f'rest frame already corrected... please set --fc as False'))
                sys.exit()
            else:
                self.Header['frame'] = args.frame
                self.Header['vel_type'] = 'VRAD'
            # correct is_rfi
            if is_rfi is not None and not args.replace_rfi:
                is_rfi, _ = frame_correct(is_rfi, self.freq, self.mjd,
                                          self.ra, self.dec, frame=args.frame, interp_kind='nearest')
                is_rfi = np.array(is_rfi, dtype=bool)
            print('frame correcting...')
            s2p, freq = frame_correct(s2p, self.freq, self.mjd, self.ra, self.dec, frame=args.frame)
            vel = freq2vel(freq)
            self.s2p_out = s2p
            self.gen_dict_out(freq=freq, vel=vel)  # replace freq, add vel
        else:
            self.s2p_out = s2p
            self.gen_dict_out()
        # save is_rfi only if replace_rfi is False
        if not args.replace_rfi and is_rfi is not None:
            self.dict_out['is_rfi'] = is_rfi
        if save:
            self.save()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    print(parser.format_values())  # useful for logging where different settings came from
    print('#'*35+'####'+'#'*35)
    io = IO(args_)
    io()