# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S5-multi.ipynb (unless otherwise specified).

__all__ = ['parser', 'IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='reference frame correction and etc.', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra file path.')
group = parser.add_argument_group(f'*frame correction\n{sep_line}')
# frame correct
group.add_argument('--fc', type=bool_fun, choices=[True, False], default='True', not_in_write_out_config_file=True,
                   help='frame correct')
group.add_argument('--frame', choices=['HELIOCEN', 'LSRK'], default='LSRK',
                   help='Velocity Rest Frames, HELIOCEN or LSRK')
group = parser.add_argument_group(f'*after\n{sep_line}')
group.add_argument('--replace_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='if True, replace spectra contaminated by rfi as np.nan')
group.add_argument('--merge_polar', type=bool_fun, choices=[True, False], default='True',
                   help='if True, average two polarization')

# Cell
class IO(BaseIO):
    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-fc'
        return fpart

    def __call__(self, save=True):
        import numpy as np
        args = self.args
        s2p = self.s2p[:]
        if args.fc:
            if 'frame' in self.Header.keys():
                raise(ValueError(f'rest frame already corrected...'))
            else:
                self.Header['frame'] = args.frame
                self.Header['vel_type'] = 'VRAD'
            from .core.corr_vel import freq2vel, frame_correct
            if 'is_rfi' in self.fs.keys():
                # if not replace_rfi, frame correct it, otherwise del it from self.dict_out at last
                is_rfi = self.fs['is_rfi'][:]
                if not args.replace_rfi:
                    is_rfi, _ = frame_correct(is_rfi, self.freq, self.mjd,
                                              self.ra, self.dec, frame=args.frame, interp_kind='nearest')
                    is_rfi = np.array(is_rfi, dtype=bool)
                else:
                    print('replacing RFI...')
                    s2p[is_rfi] = None
                    is_rfi = None
            if args.merge_polar and s2p.ndim == 3:
                print('average two polarization...')
                s2p = np.mean(s2p, axis=2, keepdims=True)
            print('frame correcting...')
            s2p, freq = frame_correct(s2p, self.freq, self.mjd, self.ra, self.dec, frame=args.frame)
            vel = freq2vel(freq)
            self.s2p_out = s2p
            self.gen_dict_out(freq=freq, vel=vel)  # replace freq, add vel
            if is_rfi is not None:
                self.dict_out['is_rfi'] = is_rfi
        else:
            if args.replace_rfi and 'is_rfi' in self.fs.keys():
                print('replacing RFI')
                s2p[self.fs['is_rfi'][:]] = None
            if args.merge_polar and s2p.ndim == 3:
                print('average two polarization')
                s2p = np.mean(s2p, axis=2, keepdims=True)
            self.s2p_out = s2p
            self.gen_dict_out()
        if args.replace_rfi and 'is_rfi' in self.dict_out.keys():
            self.dict_out.pop('is_rfi')
        if save:
            self.save()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    io = IO(args_)
    io()