# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S5-multi.ipynb (unless otherwise specified).

__all__ = ['IO']

# Cell
from .utils.io import *
import numpy as np

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='reference frame correction and etc.', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
group = parser.add_argument_group(f'*frame correction\n{sep_line}')
# frame correct
group.add_argument('--fc', type=bool_fun, choices=[True, False], default='True', not_in_write_out_config_file=True,
                   help='frame correct')
group.add_argument('--frame', choices=['BARYCENT', 'HELIOCEN', 'LSRK', 'LSRD'], default='LSRK',
                   help='Velocity Rest Frames, HELIOCEN or LSRK')
group.add_argument('--vtype', choices=['radio', 'optical'], default='optical',
                   help='velocity type')
group = parser.add_argument_group(f'*after\n{sep_line}')
group.add_argument('--replace_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='if True, replace spectra contaminated by rfi as np.nan')
group.add_argument('--merge_polar', type=bool_fun, choices=[True, False], default='True',
                   help='if True, average two polarization')
group.add_argument('--clip', type=bool_fun, choices=[True, False], default='False',
                   help='if True, clip rfi')
group.add_argument('--clip_times', type=float, nargs=2, default=[10, 50],
                   help='clip thr [rms * neg_times, rms * posi_times]')
# Cell
class IO(BaseIO):
    ver = 'old'
    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-fc'
        return fpart
    
    def get_rms(self, rms_step=5):
    
        from .ripple.markRFI import get_rms_frange, rms
        is_excluded = self.fs['is_excluded'][:]
        is_rfi = self.fs['is_rfi'][:]
        is_lf = np.all(is_rfi, axis = 1)
        data = self.s2p[~is_lf]
        data[is_excluded[~is_lf]] = np.nan

        spec = np.nanmean(np.nanmean(data, axis = 0),axis = -1)
        freq = self.freq

        rms_frange = get_rms_frange(spec, freq, rms_step= rms_step,)

        rmss = rms(data, freq, rms_frange)

        return np.nanmedian(rmss)
    
    def clip_strange(self, s2p, low = 30, high = 100):
        from .ripple.sw_fft import check_bottleneck
        bn = check_bottleneck()
        mean = bn.nanmean(s2p)
        std = self.get_rms()

        thr_low = mean - low * std
        thr_high = mean + high * std

        print("clip thr_low = ", thr_low)
        print("clip thr_high = ", thr_high)

        s2p[(s2p < thr_low) | (s2p > thr_high)] = np.nan

        return s2p

    def __call__(self, save=True):
        
        args = self.args
        s2p = self.s2p[:]
        
        # try load is_rfi
        if 'is_rfi' in self.fs.keys():
            # if not replace_rfi, frame correct it

            if self.is_use_freq is not None:
                inds = np.where(self.is_use_freq)[0]
                is_rfi = self.fs['is_rfi'][:, inds]
            else:
                is_rfi = self.fs['is_rfi'][:]
            if args.replace_rfi:
                print('replacing RFI')
                s2p[is_rfi] = np.nan
        else:
            is_rfi = None
            
        # mask Inf and strange points
        s2p[np.isinf(s2p)] = np.nan
        if args.clip:
            s2p = self.clip_strange(s2p, low = args.clip_times[0], high = args.clip_times[1])

        if args.merge_polar and s2p.ndim == 3:
            print('average two polarization...')
            s2p = np.mean(s2p, axis=2, keepdims=True)
        # frame
        if args.fc:
            from .core.corr_vel import freq2vel, correct_spec
            if 'frame' in self.Header.keys():
                raise(ValueError(f'rest frame already corrected... please set --fc as False'))
                sys.exit()
            else:
                self.Header['frame'] = args.frame
                self.Header['vel_type'] = args.vtype
            # correct is_rfi
            if is_rfi is not None and not args.replace_rfi:
                is_rfi, _ = correct_spec(is_rfi, self.freq, self.ra, self.dec, self.mjd,
                                           frame=args.frame, method='interp', interp_kind='nearest')
                is_rfi = np.array(is_rfi, dtype=bool)
            print('frame correcting...')
            s2p, freq = correct_spec(s2p, self.freq, self.ra, self.dec, self.mjd, frame=args.frame, method='interp')
            vel = freq2vel(freq, vtype=args.vtype)
            self.s2p_out = s2p
            self.gen_dict_out(freq=freq, vel=vel)  # replace freq, add vel
            if 'Tcal' in self.dict_out.keys():
                # use ``try`` to be compatible with the file generated with old version having bug
                try:
                    values = self.dict_out['Tcal'] # self.is_use_freq has been applied; still is (Mjd,Chan,Polar)
                    self.dict_out['Tcal'], _ = correct_spec(values, self.freq, self.ra, self.dec, self.mjd, frame=args.frame, method='interp')
                except:
                    pass
        else:
            self.s2p_out = s2p
            self.gen_dict_out()
        # save is_rfi only if replace_rfi is False
        if not args.replace_rfi and is_rfi is not None:
            self.dict_out['is_rfi'] = is_rfi
        else:
            if 'is_rfi' in self.dict_out.keys():
                self.dict_out.pop('is_rfi')
        if save:
            self.save()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    args_from = parser.format_values()
    print(args_from)
    print('#'*35+'####'+'#'*35)

    HistoryAdd = {'args_from': args_from} if args_.my_config is not None else None
    io = IO(args_, HistoryAdd=HistoryAdd)
    io()
