# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S2-bld.ipynb (unless otherwise specified).

__all__ = ['IO', 'IO_i']

# Cell
from .utils.io import *
import numpy as np

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract baseline', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature or flux file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")
parser.add_argument('--show_prog', type=bool_fun, choices=[True, False], default='True', env_var='HIFAST_SHOW_PROG',
                    help='')

# baseline fitting
group = parser.add_argument_group(f'*BaseLine (set --method as none to skip this) \n{sep_line}')

method = ['none']
method += ['MedMed', 'MinMed']

group.add_argument('--method', default='MedMed', choices=method,
                   help='method used to fit baseline, if set as none, skip this')


# MinMed or MedMed
group = parser.add_argument_group(f'*MinMed or MedMed\n{sep_line}')
group.add_argument('--nsection', type=int,
                   help='divide each part into n sections. Same with nspec')
group.add_argument('--nspec', type=int,
                   help='divide each part into n sections. One section has n specs.')
group.add_argument('--npart', type=int,
                   help='divide data into n parts')

# Exclude files
group = parser.add_argument_group(f'*Exclude known source catalogs\n{sep_line}')
group.add_argument('--continuum_file', 
                   help='txt catalog with #ra[deg], dec[deg], R[arcmin], freq_min[MHz], freq_max[MHz]')
group.add_argument('--HI_file', 
                   help='txt catalog with #ra[deg], dec[deg], R[arcmin], freq_min[MHz], freq_max[MHz]')
group.add_argument('--frame', choices=['BARYCENT', 'HELIOCEN', 'LSRK', 'LSRD'], default='LSRK',
                   help='Velocity Rest Frames, HELIOCEN or LSRK')


# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        return '-ref'

    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global h5py, OrderedDict, sub_baseline

        import h5py
        from collections import OrderedDict
        from .core.baseline import sub_baseline
        
    def _load_is_rfi(self,):
        fs = self.fs
        if 'is_rfi' in fs.keys():
            is_rfi = fs['is_rfi'][:]
            if self.is_use_freq is not None:
                is_rfi = is_rfi[:, self.is_use_freq]

            self.is_rfi = is_rfi

    def _load_is_excluded(self):
        fs = self.fs
        if 'is_excluded' in fs.keys():
            is_excluded = fs['is_excluded'][:]
            if self.is_use_freq is not None:
                is_excluded = is_excluded[:, self.is_use_freq]

            self.is_excluded = is_excluded
            
            
    def _load_continuum(self):
        args = self.args
        fpath = args.continuum_file
        if fpath is not None:
            from .core.regions import mask_srcs

            is_excluded = np.zeros(self.s2p.shape[:2], dtype = bool)
            print(f"loading excluded files from {fpath}")
            self.is_continum = mask_srcs(fpath, is_excluded, self.ra, self.dec, self.freq, 
                                         self.mjd, inplace=True, rest_frame=args.frame)
        
    def _load_sources(self):
        args = self.args
        fpath = args.HI_file
        if fpath is not None:
            from .core.regions import mask_srcs
            is_excluded = self.is_excluded if hasattr(self,'is_excluded') else np.zeros(self.s2p.shape[:2], dtype = bool)
            print(f"loading excluded files from {fpath}")
            self.is_excluded = mask_srcs(fpath, is_excluded, self.ra, self.dec, self.freq, 
                                         self.mjd, inplace=True, rest_frame=args.frame)

    def med_fit_baseline(self,):
        args = self.args
        # gen self.s2p_out
        s2p = self.s2p[:]
        from copy import deepcopy
        s2p_ori = deepcopy(s2p)
        
        is_excluded = deepcopy(self.is_excluded) if hasattr(self,'is_excluded') else np.zeros(self.s2p.shape[:2], dtype = bool)
        for key in ['is_rfi', 'is_continum']:
            if hasattr(self, key):
                is_excluded |= getattr(self, key)
        s2p[is_excluded] = np.nan

        from .ripple.sw_fft import minmed
        kwargs = {}
        keys = ['nsection', 'nspec', 'npart', 'method']
        for key in keys:
            kwargs[key] = getattr(args, key)
        s2p = s2p_ori - minmed(s2p, **kwargs)
        return s2p

    def gen_s2p_out(self,):
        args = self.args

        # gen self.s2p_out
        s2p = self.s2p[:]
        # is_excluded
        self._load_is_excluded()
        self._load_sources()

        # fit baseline:
        if 'Med' in args.method:
            self._load_continuum()
            
            print(f'Use {args.method} to substract baseline. Remember another linear substraction.')
            s2p = self.med_fit_baseline()
        else:
            print('no baseline method assigned, skip. Make sure the input spectra have been baselined.')
        self.s2p_out = s2p
        
    def __call__(self, save=True):
        self.gen_s2p_out()
        if hasattr(self,'is_continum'):
            print("save is_continum :D")
            self.gen_dict_out(is_continum = self.is_continum)
        else:
            self.gen_dict_out()
#             if 'is_continum' in self.dict_out.keys():
#                 args = self.args
#                 self.dict_out['is_continum'] = h5py.ExternalLink(os.path.relpath(
#                     args.fpath, os.path.dirname(self.fpath_out)), f'/S/is_continum')
        if hasattr(self,'is_excluded'):
            self.dict_out['is_excluded'] = self.is_excluded # update
        
        # save to hdf5 file
        if save:
            self.save()



# Cell

if __name__ == '__main__':
    args_ = parser.parse_args()

    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from

    print('#'*35+'Args'+'#'*35)
    args_from = parser.format_values()
    print(args_from)
    print('#'*35+'####'+'#'*35)

    HistoryAdd = {'args_from': args_from} if args_.my_config is not None else None
    io = IO(args_, HistoryAdd=HistoryAdd)
    io()
