# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S3-rfi.ipynb (unless otherwise specified).

__all__ = ['parser', 'IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='rfi', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input baselined spectra file path.')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")
# rfi
group = parser.add_argument_group(f'*Time domain RFI\n{sep_line}')
group.add_argument('--tr', '--time_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='')
group.add_argument('--tr_s_method_t', default='gaussian',
                   help='smoothing method along time axis')
group.add_argument('--tr_s_sigma_t', type=int, default=10,
                   help='')
group.add_argument('--tr_s_method_freq', default='gaussian',
                   help='smoothing method along time freq')
group.add_argument('--tr_s_sigma_freq', type=float, default=5,
                   help='')
group.add_argument('--tr_n_continue', type=int, default=100,
                   help='')
group.add_argument('--tr_times', type=float, default=6.,
                   help='')
group.add_argument('--tr_times_s', type=float, default=1.5,
                   help='')
group.add_argument('--ext_add', type=int, default=0,
                   help='extend rfi range')
group.add_argument('--ext_frac', type=float, default=0.,
                   help='between 0 and 1, extend rfi range')
# parser.add_argument('--cross_frac', type=float, default=0.,
#                    help='between 0 and 1')
group = parser.add_argument_group(f'*Polarize RFI\n{sep_line}')
group.add_argument('--pr', '--polar_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='')
group.add_argument('--pr_s_sigma', type=float, default=5,
                   help='gaussian smooth size for spectra smoothing along time axis')
group.add_argument('--pr_times', type=float, default=6,
                   help='')
group.add_argument('--pr_times_s', type=float, default=1,
                   help='')

# Cell
class IO(BaseIO):
    ver = 'old'
    def _get_fpart(self,):
        return '-rfi'

    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global h5py, OrderedDict, np

        import h5py
        from collections import OrderedDict
        import numpy as np

    def get_tr(self,):
        args = self.args
        from .core.rfi_t import mask_rfi_t
        fit_kwargs = {}
        keys = ['tr_n_continue',
                'tr_s_method_freq',
                'tr_s_method_t',
                'tr_s_sigma_freq',
                'tr_s_sigma_t',
                'tr_times',
                'tr_times_s']
        for key in keys:
            fit_kwargs[key[3:]] = getattr(args, key)

        return mask_rfi_t(self.freq, self.s2p, method='smooth', **fit_kwargs)

    def get_pr(self,):
        args = self.args
        from .core.rfi_polar import mask_rfi_p
        fit_kwargs = {}
        keys = ['pr_s_sigma',
                'pr_times',
                'pr_times_s', ]
        for key in keys:
            fit_kwargs[key[3:]] = getattr(args, key)
        return mask_rfi_p(self.s2p, **fit_kwargs)

    def gen_s2p_out(self,):
        args = self.args
        self.s2p_out = self.s2p[:]

    def __call__(self, save=True):
        args = self.args
        self.gen_s2p_out()
        self.s2p = self.s2p[:]
        if args.tr:
            print('finding tr')
            is_rfi = self.get_tr()
        else:
            is_rfi = np.full(self.s2p.shape[:2], False, dtype=bool)
        if args.pr:
            print('finding pr')
            is_rfi |= self.get_pr()
        if 'is_rfi' in self.fs.keys():
            is_rfi |= self.fs['is_rfi'][:]
        self.gen_dict_out(is_rfi=is_rfi)
        # replace outfield as h5py.ExternalLink
        if self.dict_in is None:
            self.dict_out[self.outfield] = h5py.ExternalLink(os.path.relpath(
                args.fpath, os.path.dirname(self.fpath_out)), f'/S/{self.infield}')
        if save:
            self.save()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    io = IO(args_)
    io()