# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S3-rfi.ipynb (unless otherwise specified).

__all__ = ['sep_line', 'parser', 'group', 'group']

# Cell
from .utils.io import *

# Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='rfi', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input baselined spectra file path.')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")
# rfi
group = parser.add_argument_group(f'*Time domain RFI\n{sep_line}')
group.add_argument('--tr', '--time_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='')
group.add_argument('--tr_s_method_t', default='gaussian',
                   help='smoothing method along time axis')
group.add_argument('--tr_s_sigma_t', type=int, default=10,
                   help='')
group.add_argument('--tr_s_method_freq', default='gaussian',
                   help='smoothing method along time freq')
group.add_argument('--tr_s_sigma_freq', type=float, default=5,
                   help='')
group.add_argument('--tr_n_continue', type=int, default=100,
                   help='')
group.add_argument('--tr_times', type=float, default=6.,
                   help='')
group.add_argument('--tr_times_s', type=float, default=1.5,
                   help='')
group.add_argument('--ext_add', type=int, default=0,
                   help='extend rfi range')
group.add_argument('--ext_frac', type=float, default=0.,
                   help='between 0 and 1, extend rfi range')
# parser.add_argument('--cross_frac', type=float, default=0.,
#                    help='between 0 and 1')
group = parser.add_argument_group(f'*Polarize RFI\n{sep_line}')
group.add_argument('--pr', '--polar_rfi', type=bool_fun, choices=[True, False], default='True',
                   help='')
group.add_argument('--pr_s_sigma', type=float, default=5,
                   help='gaussian smooth size for spectra smoothing along time axis')
group.add_argument('--pr_times', type=float, default=6,
                   help='')
group.add_argument('--pr_times_s', type=float, default=1,
                   help='')



# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    io = IO(args_)
    io()