# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/F-sep.ipynb (unless otherwise specified).

__all__ = ['sep_line', 'parser']

# Cell
from .utils.io import *
from glob import glob

# Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                    formatter_class=formatter_class, allow_abbrev=False,
                    description='separate Cal on and Cal off; noise-diode Calibration', )

parser.add_argument('fpath',
                    help='only need input the first chunk file path (e.g. XXX_0001.fits) of RAW spectra data')
parser.add_argument('-f', dest='force', action='store_true',
                    help='overwriting file if out file exists')
parser.add_argument('--outdir', required=True,
                   help='the directory to store output files.')
parser.add_argument('-g', is_write_out_config_file_arg=True,
                        help='save config to file path')
parser.add_argument('-c', '--my-config', is_config_file_arg=True,
                        help='config file path')

parser.add_argument('-d', '--n_delay', type=int, required=True,
                   help='time of delay divided by sampling time')
parser.add_argument('-m', '--n_on', type=int, required=True,
                   help='time of Tcal_on divided by sampling time')
parser.add_argument('-n', '--n_off', type=int, required=True,
                    help='time of Tcal_off divided by sampling time')
parser.add_argument('--frange', type=float, nargs=2,
                    help='freq range')
parser.add_argument('--step', type=int, default=5,
                   help='number of files loaded into memory every time, default 5')
parser.add_argument('--start', type=int,
                   help='chunk number of start')
parser.add_argument('--stop', type=int,
                   help='chunk number of stop')
parser.add_argument('--sep_save', action='store_true',
                   help='every step save to a file')


parser.add_argument('--smooth', choices=['mean','poly','gaussian'], required=True,
                    help="smooth method: 'mean','poly',gaussian',.. default:gaussian")
parser.add_argument('--s_sigma', type=float, default=5,
                    help='sigma for gaussian smooth, default 5MHz')
parser.add_argument('--s_deg', type=int, default=1,
                    help='Degree of the fitting polynomial, 0 equals mean; 1 is linear fit. default 1')
parser.add_argument('--ext_frange', type=bool_fun, choices=[True, False], default='True',
                    help="if True and smooth method is gaussian, then extend 1*s_sigma in the beginning and end of frange")
parser.add_argument('--dfactor',
                    help='Down-sample the data before cal Teff; str "W" or int number')
parser.add_argument('--med_filter_size', type=int,
                    help='median filter kernel size for power of spec; odd number; default None')
parser.add_argument('--noise_mode', default='high', choices=['high','low'],
                    help='noise_mode, high or low')
parser.add_argument('--noise_date', default='auto',
                    help='noise obs date, default auto')
parser.add_argument('--med_filter_size_cal', type=int, default=5,
                    help='median filter kernel size for power of cal; odd number; default 5')

parser.add_argument('--check_cal', choices=['none', 'A'], default='none',
                    help='check if cal is on continuous source')
parser.add_argument('--pcal_vary_frac', type=float, default=0.01,
                    help='If the power change near a Cal is larger than ``pcal_vary_frac``, the Cal will be abandoned in Calibration')

parser.add_argument('--merge_pcals', choices=['not', 'median'], default='not',
                    help='Whether merge pcal to calculate pcal with frequency')
parser.add_argument('--calc_diff_method', choices=['div', 'sub'], default='div',
                    help="used if '--merge_pcals' is not set as 'not'")
parser.add_argument('--squeeze_diff_freq', choices=['median', 'mean', 'sigclip_median', 'sigclip_mean'], default='sigclip_median',
                    help="method applied to the difference of pcals with the 'merged-pcals' along freq")
parser.add_argument('--method_interp', choices=['gaussian', 'slinear', 'quadratic', 'cubic', 'nearest'], default='quadratic',
                    help="Interpolate the difference to get pcal for each spectrum, used if '--merge_pcals' is not set as 'not'")
parser.add_argument('--sigma_t', type=float, default=300,
                    help='sigma_t in  ``--method_interp gaussian``')

parser.add_argument('--p_cal_fname',
                    help='input hdf5 power of cal file')
parser.add_argument('--save_p_cal', action='store_true',
                    help='save power of cal to file')

parser.add_argument('--not_cali', action='store_true',
                    help='save power data, no temperature calibration')

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    print('#'*35+'Args'+'#'*35)
    parser.format_values()
    print('#'*35+'####'+'#'*35)

    args = args_

    #check input file exits
    if not os.path.exists(args.fpath):
        raise(OSError(f'File {args.fpath} not exists.'))

    # replace patten in outdir
    nB = get_nB(args.fpath)
    project = get_project(args.fpath)
    ## use the dirname of the fits file as "date"
    date = os.path.basename(os.path.dirname(os.path.abspath(args.fpath)))
    args.outdir = sub_patten(args.outdir, date=date, nB=f'{nB:02d}', project=project)
    print(f'outdir: {args.outdir}')
    if args.outdir is not None:
        if not os.path.exists(args.outdir):
            print(f'outdir {args.outdir} not exists. Create it now')
            os.makedirs(args.outdir, exist_ok=True)

    ## check out file
    fname_add = date
    fname_part = re.sub('[0-9]{4}\.fits\Z', '', args.fpath)
    out_name_base = os.path.join(args.outdir, f"{os.path.basename(fname_part)[:-1]}-{fname_add}")
    fileout =  out_name_base + f"-specs_T.hdf5"
    fileout_sep = glob(out_name_base + rf"-specs_T_[0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9].hdf5")

    if os.path.exists(fileout) or len(fileout_sep)>0:
        if args.force:
            print(f"will overwrite the existing out file")
        else:
            print(f"File exists {fileout}")
            print(fileout_sep)
            print('exit... Using -f to overwrite it.')
            sys.exit()

    # check frange
    frange = args.frange
    if frange is not None and args.smooth == "gaussian" and args.ext_frange:
        frange = [frange[0] - args.s_sigma, frange[1] + args.s_sigma]
    args.frange = frange
    # chunk files
    if args.start is None:
        args.start = 1
    if args.stop is None:
        args.stop = len(glob(fname_part+'*.fits'))

    # cal smooth
    smooth = args.smooth #"mean", "gaussian","poly"
    s_sigma = args.s_sigma
    s_deg = args.s_deg
    if smooth == "gaussian":
        if args.frange is not None:
            if (args.frange[1] - args.frange[0])/s_sigma <3:
                raise(ValueError('s_sigma is too larger for the input freq range'))
        s_para = {'s_sigma': s_sigma,}
    if smooth == 'mean':
        smooth = 'poly'
        s_deg = 0
    if smooth == 'poly':
        s_para = {'s_deg': s_deg,}

    dfactor = args.dfactor
    if dfactor is not None and dfactor.upper() != "W":
        dfactor = int(dfactor)

    print('processing: ', fname_part)
    print('n_delay, n_on, n_off: ', end='')
    print(args.n_delay, args.n_on, args.n_off, sep=', ')
    print('freq range: ', args.frange)

    # import
    from .core.cal import CalOnOff, CalOnOffA
    from .core.cal2 import CalOnOffAA
    import json

    #record history
    header = rec_his(args=json.dumps(args.__dict__))

    # cal
    keys = ['n_delay', 'n_on', 'n_off',
            'start', 'stop',
            'frange',
            'dfactor',
            'med_filter_size',
            'noise_mode',
            'noise_date',
            'med_filter_size_cal',
            'p_cal_fname',
            ]
    paras = {key:getattr(args, key) for key in keys}
    paras['fname_part'] = fname_part
    paras['verbose'] = True
    paras['smooth'] = smooth
    paras['s_para'] = s_para

    if args.merge_pcals != 'not':
        Cal_cls = CalOnOffAA
        paras['pcal_vary_frac'] = args.pcal_vary_frac
    else:
        if args.check_cal == 'none':
            Cal_cls = CalOnOff
        elif args.check_cal == 'A':
            Cal_cls = CalOnOffA
            paras['pcal_vary_frac'] = args.pcal_vary_frac

    spec = Cal_cls(**paras)

    if args.merge_pcals != 'not':
        spec.set_para_pcals(calc_diff_method=args.calc_diff_method,
                            squeeze_diff_freq=args.squeeze_diff_freq,
                            method_interp=args.method_interp,
                            sigma_t=args.sigma_t)

    spec(outdir=args.outdir, step=args.step, header=header,
         sep_save=args.sep_save, save_p_cal=args.save_p_cal, cali=(not args.not_cali))
