# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/sub_ref.ipynb (unless otherwise specified).

__all__ = ['find_peak', 'get_ref_ind_otf', 'IO']

# Cell
import numpy as np
from matplotlib import pyplot as plt
import h5py
from .core.radec import _tight_ra

from .utils.misc import smooth1d_fft, average_every_n

from .core.baseline import get_baseline
from scipy import ndimage

# Cell
def find_peak(y, times=2):
    # ys = smooth1d_fft(np.arange(len(y)), y, 120)
    # ys = ndimage.gaussian_filter1d(y,10)
    ys = get_baseline(None, y, axis=-1, method='arPLS',
                      bl_para={'lam': 1e5, 'deg': 3, 'niter': 1})
    s, m, e = np.nanpercentile(y-ys, [16, 50, 84], axis=-1)
    is_ = (ys < m-(m-s)*times) | (ys > m+(e-m)*times)
    return is_, ys

# Cell
def get_ref_ind_otf(ra, dec, scan_dir):
    if scan_dir.lower() in ['-', 'dec']:
        is_, _ = find_peak(np.diff(dec), 2)
    elif scan_dir.lower() in ['|', 'ra']:
        is_, _ = find_peak(np.diff(ra), 2)
    ind_ref = np.arange(len(ra))[1:][is_]
    return ind_ref

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='Convert the spectra temperature to flux', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="if set, don't check or add ra dec")
group = parser.add_argument_group(f'*Flux\n{sep_line}')
group.add_argument('--mode', help='scan mode: drift or otf')
group.add_argument('--scan_dir', choices=['dec', '|', 'ra', '-'], help='scan direction in OTF mode')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-sub_ref'
        return fpart

    def gen_s2p_out(self,):
        args = self.args
        s2p = self.s2p[:]

        if args.mode.lower() == 'otf':
            ra, dec = self.ra, self.dec
            ra = _tight_ra(ra)
            # find reference spectra
            ind_ref = get_ref_ind_otf(ra, dec, args.scan_dir)
            # use the nearest reference
            ind_all = ind_ref[np.argmin(abs(np.arange(len(ra))[:, None] - ind_ref[None, :]), axis=1)]
            s2p = s2p - s2p[ind_all]
        elif args.mode.lower() == 'drift':
            s2p = s2p - np.mean(s2p[:5], axis=0)[None,:]

        self.s2p_out = s2p

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    print(parser.format_values())  # useful for logging where different settings came from
    print('#'*35+'####'+'#'*35)
    io = IO(args_)
    io()