# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/E-sub_ref_2.ipynb (unless otherwise specified).

__all__ = ['IO']

# Cell
import numpy as np
from matplotlib import pyplot as plt
import h5py
from .core.radec import _tight_ra

from .utils.misc import smooth1d_fft, average_every_n

from .core.baseline import get_baseline
from scipy import ndimage

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}", formatter_class=formatter_class, allow_abbrev=False,
                        description='Convert the spectra temperature to flux', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input spectra temperature file path.')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="if set, don't check or add ra dec")
group = parser.add_argument_group(f'*REF\n{sep_line}')
group.add_argument('--fpath_ref',
                   help='')
group.add_argument('--squeeze_group', default='mean',
                   help='mean, median')
group.add_argument('--method_interp', default='next',
                   help='next, previous')

# Cell
class IO(BaseIO):
    ver = 'old'

    def _get_fpart(self,):
        """
        need modify this function
        """
        fpart = '-sub_ref'
        return fpart
    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global np, interp
        from scipy import interpolate as interp
        import numpy as np

    def gen_ref(self):
        import h5py
        fpath_ref = self.args.fpath_ref
        with h5py.File(fpath_ref, 'r') as f:
            inds_ref = f['S']['inds_ref'][:]
            start_stop_groups = f['S']['start_stop_groups'][:]
            mjd = f['S']['mjd'][:]

        inds_groups = np.split(np.arange(len(mjd)), start_stop_groups.flatten())[1::2]
        inds_groups = list(map(lambda d:d[np.isin(d, inds_ref)], inds_groups))
        self.ref_inds_groups = inds_groups
        self.ref_inds_center = np.mean(start_stop_groups, axis=1)

    @staticmethod
    def squeeze_groups(arr, inds_groups, method='mean'):
        if method == 'mean':
            func = np.mean
        elif method == 'median':
            func = np.median
        Squeeze = lambda inds:func(arr[inds], axis=0)
        return np.stack(list(map(Squeeze, inds_groups)))

    def gen_s2p_out(self,):
        args = self.args
        s2p = self.s2p[:]
        self.gen_ref()
        spec_ref = self.squeeze_groups(s2p, self.ref_inds_groups, method=args.squeeze_group)
        s2p -= interp.interp1d(self.ref_inds_center, spec_ref, fill_value="extrapolate", axis=0,
                               kind=args.method_interp)(np.arange(len(self.mjd)))
        self.s2p_out = s2p

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    print('#'*35+'Args'+'#'*35)
    print(parser.format_values())  # useful for logging where different settings came from
    print('#'*35+'####'+'#'*35)
    io = IO(args_)
    io()
