# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/sub_ref.ipynb (unless otherwise specified).

__all__ = ['find_peak', 'get_ref_ind_otf']

# Cell
import numpy as np
from matplotlib import pyplot as plt
import h5py
from .core.radec import _tight_ra

from .utils.misc import smooth1d_fft, average_every_n

from .core.baseline import get_baseline
from scipy import ndimage

# Cell
def find_peak(y, times=2):
    # ys = smooth1d_fft(np.arange(len(y)), y, 120)
    # ys = ndimage.gaussian_filter1d(y,10)
    ys = get_baseline(None, y, axis=-1, method='arPLS',
                      bl_para={'lam': 1e5, 'deg': 3, 'niter': 1})
    s, m, e = np.nanpercentile(y-ys, [16, 50, 84], axis=-1)
    is_ = (ys < m-(m-s)*times) | (ys > m+(e-m)*times)
    return is_, ys

# Cell
def get_ref_ind_otf(ra, dec, scan_dir):
    if scan_dir.lower() in ['-', 'dec']:
        is_, _ = find_peak(np.diff(dec), 2)
    elif scan_dir.lower() in ['|', 'ra']:
        is_, _ = find_peak(np.diff(ra), 2)
    ind_ref = np.arange(len(ra))[1:][is_]
    return ind_ref

# Cell
if __name__ == '__main__':
    import h5py
    import argparse
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument('fname',
                        help='file name')
#     parser.add_argument('-f', '--force', action='store_true',
#                         help='overwriting file if out file exists')
    parser.add_argument('--mode',
                        help='scan mode: drift or otf')
    parser.add_argument('--scan_dir', choices=['dec', '|', 'ra', '-'],
                        help='scan direction in OTF mode')
#     parser.add_argument('--outdir',
#                         help='default is same with the input file')
    args = parser.parse_args()
    # open file
    f = h5py.File(args.fname, 'r+')
    T = f['Ta'][:]
    if args.mode.lower() == 'otf':
        ra, dec = f['ra'][()], f['dec'][()]
        ra = _tight_ra(f['ra'][:])
        # find reference spectra
        ind_ref = get_ref_ind_otf(ra, dec, args.scan_dir)
        # use the nearest reference
        ind_all = ind_ref[np.argmin(abs(np.arange(len(ra))[:, None] - ind_ref[None, :]), axis=1)]
        T = T - T[ind_all]
    elif args.mode.lower() == 'drift':
        T = T - np.mean(T[:5], axis=0)[None,:]
