# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S4-sw.ipynb (unless otherwise specified).

__all__ = ['sep_line', 'parser', 'group', 'group', 'group', 'group']

# Cell
from .utils.io import *

# Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract standing wave', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input baselined spectra file path')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="don't check or add ra dec")

# group = parser.add_argument_group(f'*Flux\n{sep_line}')
# group.add_argument('--flux', type=bool_fun, choices=[True, False], default='False',
#                    help='if True, convert  the temperature to flux before subtract baseline')
# group.add_argument('--cali_fname', default='none',
#                    help='quasar calibration file name')

# baseline fitting
# standing wave
group = parser.add_argument_group(f'*Sinusoidal standing wave (set --method_2 as none to skip this)\n{sep_line}')
group.add_argument('--method', default='sin_poly', choices=['none', 'sin_poly', 'sin_poly_2'],
                   help='method to fit standing wave')
# group.add_argument('--only_sub', type=bool_fun, choices=[True, False], default='True',
#                    help='if True, only subtract standing wave, not baseline')
group = parser.add_argument_group('preprocessing before sinusoidal standing wave (sw) fitting')
group.add_argument('--njoin', type=int, default=0,
                   help='join nspec along t')
group.add_argument('--s_method_t', default='none', choices=['none', 'gaussian', 'boxcar', 'median'],
                   help='')
group.add_argument('--s_sigma_t', type=int, default=5,
                   help='')
group.add_argument('--s_method_freq', default='none', choices=['none', 'median', 'gaussian', 'boxcar'],
                   help='')
group.add_argument('--s_sigma_freq', type=float, default=5,
                   help='')
group.add_argument('--average_every_freq', type=int, default=0,
                   help='')
group = parser.add_argument_group('sinusoidal standing wave (sw) fitting')
group.add_argument('--exclude_m', type=int, default=0,
                   help='')
group.add_argument('--sin_f', type=float, nargs='+', default=0.929,
                   help='sin freq')
group.add_argument('--deg', type=int, default=1,
                   help='baseline fit parameters')
# interaction
group = parser.add_argument_group(f'*Interaction\n{sep_line}')
group.add_argument('-i', '--interact', action='store_true', not_in_write_out_config_file=True,
                   help='interaction')

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    io = IO(args_)
    #io()