# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/S4-sw.ipynb (unless otherwise specified).

__all__ = ['parser', 'IO']

# Cell
from .utils.io import *
#nbdev_comment _all_ = ['parser']

# Internal Cell
sep_line = '##'+'#'*70+'##'
parser = ArgumentParser(prog=f"python -m hifast.{os.path.basename(sys.argv[0])[:-3]}",
                        formatter_class=formatter_class, allow_abbrev=False,
                        description='Fit and subtract standing wave', )
add_common_argument(parser)
parser.add_argument('fpath',
                    help='input baselined spectra file path')
parser.add_argument('--frange', type=float, nargs=2, default=[0, float('inf')],
                    help='Limit frequence range')
parser.add_argument('--no_radec', action='store_true', not_in_write_out_config_file=True,
                    help="if set, don't check or add ra dec")
parser.add_argument('--nproc', '-n', type=int, default=1,
                    help='number of process used in fitting baseline')

# method
group = parser.add_argument_group(f'*select method used to fit standing wave\n{sep_line}')
group.add_argument('--method', default='sin_poly', choices=['sin_poly', 'fft'],
                   help='method to fit standing wave')
group.add_argument('--nobld', type=bool_fun, choices=[True, False], default='False',
                   help="if True, use the spectra before bld to subtract standing wave and output file name will add 'nobld'")
group.add_argument('--fpattern_nobld',
                   help='if not specify, guess from the History recored in the fpath')
# group.add_argument('--only_sub', type=bool_fun, choices=[True, False], default='True',
#                    help='if True, only subtract standing wave, not baseline')
group = parser.add_argument_group('  preprocessing before fitting')
group.add_argument('--s_method_t', default='none', choices=['none', 'gaussian', 'boxcar', 'median'],
                   help='')
group.add_argument('--s_sigma_t', type=int, default=5,
                   help='')
group.add_argument('--s_method_freq', default='none', choices=['none', 'median', 'gaussian', 'boxcar'],
                   help='')
group.add_argument('--s_sigma_freq', type=float, default=5,
                   help='')
group.add_argument('--average_every_freq', type=int, default=0,
                   help='')
# least square
group = parser.add_argument_group(f'*parameters for --method sin_poly\n{sep_line}:' +
                                  '\n'+'addition options for preprocessing before fitting')
group.add_argument('--njoin', type=int, default=10,
                   help='join nspec along t')
group = parser.add_argument_group('sinusoidal standing wave (sw) fitting')
group.add_argument('--exclude_m', type=int, default=0,
                   help='')
group.add_argument('--sin_f', type=float, nargs='+', default=0.929,
                   help='Initial guess for sw freq')
group.add_argument('--bound_f', type=float, nargs=2, default=[.90, .95],
                   help='Lower and upper bounds for sw freq')
group.add_argument('--deg', type=int, default=1,
                   help='Degree of the added polynomial')
# fft
group = parser.add_argument_group(f'*parameters for --method fft\n{sep_line}:' +
                                  '\n'+'replace big RFI or sources firstly')
# replace big RFI or sources firstly
group.add_argument('--rfi_method', default='near_ripple', choices=['near_ripple'],
                   help='method to replace big RFI')
group.add_argument('--mw_frange', type=float, nargs=2, default=[1419, 1422],
                   help='milky way freq range, or None')
group.add_argument('--rms_sigma', type=float, default=6,
                   help='gauss filter sigma to compute real rms')
group.add_argument('--rms_frange', type=float, nargs=2,
                   help='freq range to compute rms')
group.add_argument('--times_lower_thr', type=float, default=4,
                   help='above * times of rms will be lowered')
group.add_argument('--ext_freq', type=float, default=1.3,
                   help='extend freq range to replace (mhz)')
group.add_argument('--rfi_width_lim', type=float, default=15,
                   help='rfi should contain more channels than limit')
group.add_argument('--ext_sec', type=int, default=20,
                   help='extend channel number of start and end of each section')

group = parser.add_argument_group(f'phase space')

# remove which component in fft? (only 4 types now)
group.add_argument('--sw_base', type=bool_fun, choices=[True, False], default='True',
                   help='if True, remove constant components')
group.add_argument('--sw_periods', nargs='+', choices=['1mhz', '2mhz', '0_04mhz'], default=['1mhz', '2mhz', '0_04mhz'],
                   help='remove ripple (1mhz: 1.08mhz, 2mhz:1.92mhz, 0_04mhz: 0.039 mhz)')
group.add_argument('--check_2mhz', type=bool_fun, choices=[True, False], default='True',
                   help='if True, remove 2mhz from sw_periods except for Beam 6')
# group.add_argument('--rip_1mhz', action='store_true',
#                    help='remove 1.08mhz ripple')
# group.add_argument('--rip_2mhz', action='store_true',
#                    help='remove 1.92mhz ripple')
# group.add_argument('--rip_0_04mhz', action='store_true',
#                    help='remove 0.039 mhz ripple')

group.add_argument('--amp_thr_mean_factor', type=float, default=1.05,
                   help='above mean amptitude threshold will be chosed')
group.add_argument('--amp_thr_solo_factor', type=float, default=1.4,
                   help='above amptitude threshold will be chosed in every spec')
group.add_argument('--chan_wide', type=int, default=5,
                   help='channel numbers near 1mhz to be chosed (wide)')
group.add_argument('--chan_narr', type=int, default=3,
                   help='channel numbers near 1mhz to be chosed (narrow)')
group.add_argument('--choose_method', default='all', choices=['all', 'interpolate'],
                   help='method to choose components in fft')

# interaction
group = parser.add_argument_group(f'*Interaction\n{sep_line}')
group.add_argument('-i', '--interact', action='store_true', not_in_write_out_config_file=True,
                   help='interaction')
group.add_argument('--ylim', nargs='+', default=['auto'], not_in_write_out_config_file=True,
                   help='ylim')
group.add_argument('--figsize', type=float, nargs=2, default=(10, 7), not_in_write_out_config_file=True,
                   help='figsize')
group.add_argument('--length', type=int, default=40, not_in_write_out_config_file=True,
                   help='spetra numbers used to test')

# Cell
class IO(BaseIO):
    ver = 'old'

    def __init__(self, *args, dict_bef_bld=None, **kwargs):
        self.dict_bef_bld = dict_bef_bld
        super().__init__(*args, **kwargs)

    def _get_fpart(self,):
        if self.args.nobld:
            return '-sw_nobld'
        return '-sw'

    def _import_m(self,):
        """
        need modify this function
        """
        super()._import_m()
        global h5py, np, OrderedDict, sub_baseline, get_exclude_fun
        import h5py
        import numpy as np
        from collections import OrderedDict
        from .core.baseline import sub_baseline, get_exclude_fun

    @staticmethod
    def find_fname_his(Header, fname):
        """
        from historys in Header to find file:
        return: [path, path related to the 'outdir' in history]
        """
        import json
        fpath_in_list = []
        outdir_list = []
        cwd_list = []
        for key in Header.keys():
            if key.startswith('HISTORY'):
                his = json.loads(Header[key])
                try:
                    args_h = json.loads(his['args'])
                    fpath_in_list += [args_h['fpath']]
                    outdir_list += [args_h['outdir']]
                    cwd_list += [his['cwd']]
                except:
                    try:
                        import re
                        fpath_in_list += [re.findall(r'fpath=.*.hdf5', his['args'])[0].split('=')[1][1:]]
                        outdir_list += [re.findall(r'outdir=[^,]*', his['args'])[0].split('=')[1][1:-1]]
                        cwd_list += [his['cwd']]
                    except:
                        pass
        for i, val in enumerate(fpath_in_list):
            if os.path.basename(val) == fname:
                path_ = os.path.abspath(os.path.join(cwd_list[i], val))
                out = [path_, os.path.relpath(path_, os.path.join(cwd_list[i], outdir_list[i]))]
                break
        return out

    def _gen_s2p_ori_fpath(self,):
        """
        find file path of spectra before baseline subtracted
        """
        args = self.args
        if args.fpattern_nobld is not None:
            print('using the path from --fpattern_nobld as the spectra file before baseline subtracted')
            ori_fpath = self.replace_nB(args.fpattern_nobld, self.nB)
            if not os.path.exists(ori_fpath):
                raise(FileNotFoundError(f'file {ori_fpath} not exists'))

        else:
            print('guess the path of the spectra file before baseline subtracted from the History')
            fname_find = os.path.basename(args.fpath).rsplit('bld')[0][:-1] + '.hdf5'
            ori_fpaths = self.find_fname_his(self.Header, fname_find)
            if os.path.exists(ori_fpaths[0]):
                ori_fpath = ori_fpaths[0]
            elif os.path.exists(ori_fpaths[1]):
                ori_fpath = ori_fpaths[1]
            else:
                raise(FileNotFoundError("can't find the spectra file before baseline subtracted, \
                                        please specify --fpattern_nobld"))
        self.s2p_ori_fpath = ori_fpath
        self.Header['ori_fpath'] = self.s2p_ori_fpath

    def _load_s2p_ori(self):
        """
        load spectra before baseline subtracted
        """
        if self.dict_in is None:
            self._gen_s2p_ori_fpath()
            print(f'load the spectra before baseline subtracted from: \n{self.s2p_ori_fpath}')
            f = h5py.File(self.s2p_ori_fpath, 'r')
        else:
            if self.dict_bef_bld is None:
                raise(ValueError('need input dict_bef_bld'))
            f = self.dict_bef_bld
        freq = f['freq'][:]
        s2p_ori = f[self.outfield]
        is_use_freq = (freq >= self.freq.min()) & (freq <= self.freq.max())
        if not np.all(is_use_freq):
            inds = np.where(is_use_freq)[0]
            s2p_ori = s2p_ori[..., inds[0]:inds[-1]+1]  # freq axis at end
        s2p_ori = PolarMjdChan_to_MjdChanPolar(s2p_ori)
        return s2p_ori

    @staticmethod
    def fit_sw(s2p, freq, args, subtract):
        fit_kwargs = {}
        keys = ['method',
                'njoin', 's_method_t', 's_sigma_t', 's_method_freq', 's_sigma_freq',
                'deg', 'sin_f']
        for key in keys:
            fit_kwargs[key] = getattr(args, key)
        fit_kwargs['nproc'] = args.nproc
        fit_kwargs['rew'] = False
        fit_kwargs['niter'] = 1
        if args.method == 'sin_poly':
            # sin_poly: optimize.minimize
            bounds = [(0., 1.), args.bound_f, (0, 2*np.pi), (-1, 1)] + [(-np.inf, np.inf), ]*args.deg
        opt_para = {'bounds': bounds, }
        fit_kwargs['exclude_fun'] = get_exclude_fun(args.exclude_m)
        return sub_baseline(freq, s2p, subtract=subtract, opt_para=opt_para, **fit_kwargs)

    @staticmethod
    def do_smooth(T, s_method_t, s_sigma_t, s_method_freq, s_sigma_freq):
        from .utils.misc import smooth1d
        if s_method_t in ['gaussian', 'boxcar', 'median']:
            print('Smooth ing ...')
            T = smooth1d(T, axis=0, sigma=s_sigma_t, method=s_method_t)

        if s_method_freq in ['gaussian', 'boxcar', 'median']:
            print('Smooth ing ...')
            T = smooth1d(T, axis=1, sigma=s_sigma_freq, method=s_method_freq)
        return T

    def fft_fit_sw(self, s1p, is_rfi=None, is_on=None,):
        from .ripple import sw_fft
        args = self.args

        # smooth
        s1p = self.do_smooth(s1p, args.s_method_t, args.s_sigma_t, args.s_method_freq, args.s_sigma_freq)
        # replace rfi and mw
        # replace args
        rep_args = {}
        if args.rfi_method in ['near_ripple']:
            keys = ['rms_sigma', 'rms_frange', 'times_lower_thr', 'rfi_width_lim',
                    'ext_sec', 'ext_freq', 'mw_frange', ]
        else:
            raise(ValueError('not supported rfi_method'))
        for key in keys:
            rep_args[key] = getattr(args, key)
        s1p = sw_fft.replace_rfi(s1p, self.freq, time_rfi=is_rfi, method=args.rfi_method, **rep_args)

        # fit args
        fft_args = {}
        keys = ['amp_thr_mean_factor', 'amp_thr_solo_factor', 'chan_wide', 'chan_narr',  'choose_method',
                'choose_method', 'sw_periods', 'sw_base']
        for key in keys:
            fft_args[key] = getattr(args, key)
        if args.check_2mhz:
            print('checking 2mhz')
            try:
                fft_args['sw_periods'].remove('2mhz')
            except:
                pass
            if self.nB in [6, ]:
                fft_args['sw_periods'].insert(-1, '2mhz')
            else:
                print('beam number !=6, remove 2mhz in sw_periods if it exists')
        fft_args['is_on'] = is_on
        fft_args['is_excluded_mean'] = np.all(is_rfi, axis=1) if is_rfi is not None else None
        return sw_fft.fit_sw_fft(s1p, self.freq, args.nproc, **fft_args)

    def gen_s2p_out(self,):
        args = self.args
        # gen self.s2p_out
        s2p = self.s2p[:]
        # fit baseline:
        if args.method in ['sin_poly', ]:
            print('standing wave fitting and substract')
            if args.nobld:
                self.s2p_out = self._load_s2p_ori()[:] - self.fit_sw(s2p, self.freq, args, subtract=False)
            else:
                self.s2p_out = self.fit_sw(s2p, self.freq, args, subtract=True)

        elif args.method == 'fft':
            print('standing wave fitting and substract')
            # load is_rfi, is_on
            dict_ = self.fs if self.dict_in is None else self.dict_in
            is_rfi = dict_['is_rfi'][:] if 'is_rfi' in dict_.keys() else None
            if is_rfi is not None and self.is_use_freq is not None:
                is_rfi = is_rfi[:, self.is_use_freq]
            is_on = dict_['is_on'][:]
            s2p_out = self._load_s2p_ori()[:] if args.nobld else s2p
            for i in range(s2p_out.shape[2]):
                s2p_out[..., i] -= self.fft_fit_sw(s2p_out[..., i], is_rfi, is_on)
            self.s2p_out = s2p_out

# Internal Cell
def check_backend():
    import matplotlib as mpl
    if 'ipympl' not in mpl.get_backend():
        print('Please run interaction in Jupyert and \'%matplotlib ipympl\' in the notebook cell ')
        sys.exit()


def interact(args):
    check_backend()
    import h5py
    from .interaction import sw_i as interact
    f = h5py.File(args.fpath, 'r')
    fs = f['S']
    if 'T' in fs.keys():
        T = fs['T']
    elif 'Ta' in fs.keys():
        T = fs['Ta']
    elif 'flux' in fs.keys():
        T = fs['flux']
    interact.T2p = T
    interact.freq = fs['freq'][:]
    interact.frange = args.frange
    interact.nproc = args.nproc
    interact.length = args.length
    interact.figsize = args.figsize
    interact.ylim = args.ylim[0] if len(args.ylim) == 1 else args.ylim
    interact.main()
    # sys.exit()

# Cell
if __name__ == '__main__':
    args_ = parser.parse_args()
    # print(parser.format_help())
    # print("----------")
    # print(parser.format_values())  # useful for logging where different settings came from
    if args_.interact:
        interact(args_)
    else:
        io = IO(args_)
        io()