## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --frange; default: [0, inf]; Limit frequence range
frange = [0, inf]

## *downsample
## ##########################################################################
#help: --chan_factor; default: 0; down sample on channel
chan_factor = 3
#help: --spec_factor; default: 0; down sample on spec
spec_factor = 0

