# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/interaction/bld_i.ipynb (unless otherwise specified).

__all__ = ['Test', 'phrase_ylim', 'main']

# Cell
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt
import h5py

import re
import os
from glob import glob

from ..core.baseline import get_baseline, sub_baseline
from ..utils.io import PolarMjdChan_to_MjdChanPolar
from .widgets import *

import warnings
warnings.filterwarnings("ignore", r'overflow encountered in exp')

# Cell
class Test(object):
    def __init__(self, T2p, freq, frange=None, is_excluded=None):

        if T2p.ndim != 3:
            raise(ValueError('T2p should be 3 dim'))
        self.T2p = T2p
        self.is_excluded = is_excluded
        freq = freq[:]
        if frange is not None:
            self.is_use = (freq > frange[0]) & (freq < frange[1])
            self.freq = freq[self.is_use]
        else:
            self.is_use = None
            self.freq = freq
        self.select()

    def select(self, start=0, length=20, polar=0):
        self.T2p_t = PolarMjdChan_to_MjdChanPolar(self.T2p[polar:polar+1, start:start+length])
        if self.is_excluded is not None:
            if self.is_excluded.shape == self.T2p.shape:
                self.is_excluded_t = PolarMjdChan_to_MjdChanPolar(self.is_excluded[polar:polar+1, start:start+length])
            elif self.is_excluded.ndim == 2 and self.is_excluded.shape == T2p.shape[1:]:
                self.is_excluded_t = self.is_excluded[start:start+length][...,None]
            else:
                raise('shape of ``is_excluded``')
        else:
            self.is_excluded_t = None

        if self.is_use is not None:
            self.T2p_t = self.T2p_t[:, self.is_use]
            if self.is_excluded_t is not None:
                self.is_excluded_t = self.is_excluded_t[:, self.is_use]

    def sub(self, x, start=0, length=20, polar=0, **kwargs):
        self.select(start, length, polar)
        self.bld = sub_baseline(self.freq, self.T2p_t, is_excluded=self.is_excluded_t,
                                verbose=False, **kwargs)
        return np.full(x.shape, np.nan)

    def get_ori(self, x, i, **kwargs):
        res = self.T2p_t[i, :, 0]
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

    def get_bld(self, x, i, **kwargs):
        res = self.bld[i, :, 0]
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

    def get_bl(self, x, i,  **kwargs):
        return self.T2p_t[i, :, 0] - self.bld[i, :, 0]

    def get_bld_mean(self, x, start_stop,  **kwargs):
        start, stop = start_stop
        res = np.mean(self.bld[int(start):int(stop)+1, :, 0], axis=0)
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

# Cell
def phrase_ylim(ylim, vals):

    ylim = list(map(lambda x: float(x) if 'per' != str(x)[:3] else
                    np.nanpercentile(vals, float(str(x)[3:]), interpolation='nearest'), ylim))
    return ylim

# Cell
def main():
    global ylim

    tes = Test(T2p, freq, frange, is_excluded)

    rew_type = ['asym1', 'asym2', 'asym3', 'sym1',]
    method = ['PLS-'+r for r in rew_type]
    method += ['poly-'+r for r in rew_type]
    method += ['masPLS-'+r for r in rew_type]
    method += ['asPLS',]

    sliders = {}
    sliders.update(_BoundedIntText(
        start=(0, 0, tes.T2p.shape[1]-length, 1), polar=(0, 0, 1, 1)))
    sliders.update(_IntSlider(njoin=(0, 1, length, 1)))
    sliders.update(_Dropdown(method=method,
                             s_method_freq=('gaussian', 'boxcar', 'none'),
                             s_method_t=('none', 'gaussian', 'boxcar'),
                             ))
    sliders.update(_IntSlider(s_sigma_freq=(3, 1, 20, 1), s_sigma_t=(3, 1, 20, 1)))
    sliders.update(_FloatLog10Slider(lam=(1e8, 5, 13, 0.2), readout_format='.2e'))
    sliders.update(_IntSlider(deg=(2, 1, 10, 1),
                              niter=(100, 1, 200, 1)))
    sliders.update(_FloatSlider(offset=(2, 0.1, 4, 0.1),))



    plt.ioff()
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=figsize)

    if isinstance(ylim, str):
        if ylim == 'auto':
            ylim = phrase_ylim(['per0.1', 'per99.5'], tes.T2p_t)
        elif ylim == 'full':
            ylim = 'fixed'
    else:
        ylim = phrase_ylim(ylim, tes.T2p_t)

    if isinstance(ylim, str):
        ylim2 = ylim
    else:
        ylim2 = [(ylim[0]-ylim[1])/2, (ylim[1]-ylim[0])/2]
    xlim = [tes.freq.min(), tes.freq.max()]

    # bld parameter
    # slider_formats = {'lam': "{:.2e}",
    #                   'njoin': "{:d}",
    #                   }

    controls = iplt.plot(tes.freq, tes.sub, nproc=nproc, length=length,
                         **sliders,
                         color='r', linewidth=2, xlim=xlim, ylim=ylim, ax=ax1, play_buttons=True, display_controls=False)

    widget_i = _IntSlider(i=(0, 0, length-1, 1))['i'] if length ==1 else range(length)

    controls2 = iplt.plot(tes.freq, tes.get_ori, i=widget_i,
                          controls=controls, xlim=xlim, ylim=ylim, ax=ax1, display_controls=False, play_buttons=True)
    controls3 = iplt.plot(tes.freq, tes.get_bl,
                          controls=controls2, xlim=xlim, ylim=ylim, ax=ax1)

    iplt.plot(tes.freq, tes.get_bld,
              controls=controls2, xlim=xlim, ylim=ylim2, ax=ax2)
    plt.axhline(y=0,)

    controls4 = iplt.plot(tes.freq, tes.get_bld_mean, start_stop=('r', 0, length, 11),
                          controls=controls, xlim=xlim, ylim=ylim2, ax=ax3)

    plt.axhline(y=0, )
    ax1.set_title('origial spectra', fontsize=8)
    ax2.set_title('spectra after baseline removed', fontsize=8)

    fig.tight_layout()

    w = controls.controls
    hbs = [
        widgets.HBox([widgets.Label(value=f"1. Select spectra from $start$(max:{controls.controls['start'].max}) to $start+{length}$ to fit:"),
                      w['start'], w['polar']]),
        widgets.HBox([widgets.Label(value=f"2. Fitting:"), w['njoin'], w['offset']]),
        widgets.HBox([w['s_method_t'], w['s_sigma_t'],
                     w['s_method_freq'], w['s_sigma_freq']]),
        widgets.HBox([w['method'], w['lam'], w['deg'], w['niter']]),
        widgets.HBox(
            [widgets.Label(value=f"3. Show one spectra in top and middle panels:"), w['i']]),
        widgets.HBox([widgets.Label(
            value=f"4. Show the stack spectra of in the range in the bottom panel:"), w['start_stop']]),
    ]

    BOX = widgets.VBox(hbs)
    display(BOX)
    plt.show()
    display(BOX)

    return tes
