# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/I__sw_i.ipynb (unless otherwise specified).

__all__ = ['Test', 'phrase_ylim', 'main']

# Cell
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt
import h5py

import re
import os
from glob import glob

from ..core.baseline import get_baseline, sub_baseline, get_exclude_fun
from ..utils.io import PolarMjdChan_to_MjdChanPolar
from .widgets import *

import warnings
warnings.filterwarnings("ignore", r'overflow encountered in exp')

# Internal Cell
T2p = None
freq = None
frange = None
nproc = 10

length = 20
figsize = (10, 7)
ylim = 'auto'

# Cell
class Test(object):
    def __init__(self, T2p, freq, frange=None):

        self.T2p = T2p
        freq = freq[:]
        if frange is not None:
            self.is_use = (freq > frange[0]) & (freq < frange[1])
            self.freq = freq[self.is_use]
        else:
            self.is_use = None
            self.freq = freq
        self.select()

    def select(self, start=0, length=20, polar=0):
        self.T2p_t = PolarMjdChan_to_MjdChanPolar(self.T2p[polar:polar+1, start:start+length])
        if self.is_use is not None:
            self.T2p_t = self.T2p_t[:, self.is_use]

    def sub(self, x, start=0, length=20, polar=0, bound_f=None, exclude_m=0, **kwargs):
        self.select(start, length, polar)
        bounds = [(0.,1.), bound_f, (0, 2*np.pi), (-1,1)] + [(-np.inf, np.inf),]*kwargs['deg'] # optimize.minimize
        opt_para = {'bounds':bounds,}
        self.bld = sub_baseline(self.freq, self.T2p_t, opt_para=opt_para, method='sin_poly', rew=False, niter=1,
                                verbose=False, exclude_fun=get_exclude_fun(exclude_m), **kwargs)
        return np.full(x.shape, np.nan)

    def get_ori(self, x, i, **kwargs):
        res = self.T2p_t[i, :, 0]
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

    def get_bld(self, x, i, **kwargs):
        res = self.bld[i, :, 0]
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

    def get_bl(self, x, i,  **kwargs):
        return self.T2p_t[i, :, 0] - self.bld[i, :, 0]

    def get_bld_mean(self, x, start_stop,  **kwargs):
        start, stop = start_stop
        res = np.mean(self.bld[int(start):int(stop)+1, :, 0], axis=0)
        return np.vstack([res, ndimage.gaussian_filter1d(res, 3)]).T

# Cell
def phrase_ylim(ylim, vals):

    ylim = list(map(lambda x: float(x) if 'per' != str(x)[:3] else
                    np.nanpercentile(vals, float(str(x)[3:]), interpolation='nearest'), ylim))
    return ylim

# Cell
def main():
    global ylim

    tes = Test(T2p, freq, frange)

    sliders = {}
    sliders.update(_BoundedIntText(
        start=(0, 0, tes.T2p.shape[1]-1-length, 1), polar=(0, 0, 1, 1)))
    sliders.update(_IntSlider(njoin=(0, 1, length, 1)))
    sliders.update(_Dropdown(s_method_freq=('none', 'gaussian', 'boxcar'),
                             s_method_t=('none', 'gaussian', 'boxcar'),
                             ))
    sliders.update(_IntSlider(s_sigma_freq=(3, 1, 20, 1), s_sigma_t=(3, 1, 20, 1)))
    sliders.update(_FloatSlider(sin_f=(0.929, 0.910, 0.940, 0.002), readout_format='.3f'))
    sliders.update(_IntSlider(deg=(0, 0, 5, 1),
                              exclude_m=(0, 0, 1, 1)))
    sliders.update(_FloatRangeSlider(bound_f=([.90, .95], 0.8, 1.15, 0.02), readout_format='.3f',))
    #sliders.update(_BoundedFloatText(bound_f=(0.95, 0.85, 0.99, 0.002)))


    plt.ioff()
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=figsize)

    if isinstance(ylim, str):
        if ylim == 'auto':
            ylim = phrase_ylim(['per0.1', 'per99.5'], tes.T2p_t)
        elif ylim == 'full':
            ylim = 'fixed'
    else:
        ylim = phrase_ylim(ylim, tes.T2p_t)

    if isinstance(ylim, str):
        ylim2 = ylim
    else:
        ylim2 = [(ylim[0]-ylim[1])/2, (ylim[1]-ylim[0])/2]
    xlim = [tes.freq.min(), tes.freq.max()]

    # bld parameter
    # slider_formats = {'lam': "{:.2e}",
    #                   'njoin': "{:d}",
    #                   }

    controls = iplt.plot(tes.freq, tes.sub, nproc=nproc, length=length,
                         **sliders,
                         color='r', linewidth=2, xlim=xlim, ylim=ylim, ax=ax1, play_buttons=True, display_controls=False)

    controls2 = iplt.plot(tes.freq, tes.get_ori, i=range(length),
                          controls=controls, xlim=xlim, ylim=ylim, ax=ax1, display_controls=False, play_buttons=True)
    controls3 = iplt.plot(tes.freq, tes.get_bl,
                          controls=controls2, xlim=xlim, ylim=ylim, ax=ax1)

    iplt.plot(tes.freq, tes.get_bld,
              controls=controls2, xlim=xlim, ylim=ylim2, ax=ax2)
    plt.axhline(y=0,)

    controls4 = iplt.plot(tes.freq, tes.get_bld_mean, start_stop=('r', 0, length, 11),
                          controls=controls, xlim=xlim, ylim=ylim2, ax=ax3)

    plt.axhline(y=0, )
    ax1.set_title('origial spectra', fontsize=8)
    ax2.set_title('spectra after baseline removed', fontsize=8)

    fig.tight_layout()

    w = controls.controls
    hbs = [
        widgets.HBox([widgets.Label(value=f"1. Select spectra from $start$(max:{controls.controls['start'].max}) to $start+{length}$ to fit:"),
                      w['start'], w['polar']]),
        widgets.HBox([widgets.Label(value=f"2. Fitting:"), w['njoin'], ]),
        widgets.HBox([w['s_method_t'], w['s_sigma_t'],
                     w['s_method_freq'], w['s_sigma_freq']]),
        widgets.HBox([w['exclude_m'], w['deg'], w['sin_f'], w['bound_f']]),
        widgets.HBox(
            [widgets.Label(value=f"3. Show one spectra in top and middle panels:"), w['i']]),
        widgets.HBox([widgets.Label(
            value=f"4. Show the stack spectra of in the range in the bottom panel:"), w['start_stop']]),
    ]

    BOX = widgets.VBox(hbs)
    display(BOX)
    plt.show()
    display(BOX)