# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05.utils.io.ipynb (unless otherwise specified).

__all__ = ['formatter_class', 'os', 'sys', 'ArgumentParser', 'argparse', 'formatter_class', 'bool_fun',
           'add_common_argument', 'rec_his', 'save_dict_hdf5', 'load_hdf5_to_dict', 'get_nB', 'replace_nB', 'BaseIO']

# Cell
import os
import sys
import re
import copy
from .conf_arg import ArgumentParser, argparse
# from configargparse import ArgumentParser
# import argparse
formatter_class = argparse.ArgumentDefaultsHelpFormatter

#nbdev_comment _all_ = ['os', 'sys', 'ArgumentParser', 'argparse', 'formatter_class']

# Cell
def bool_fun(s):
    """
    used as the type of parser.add_argument
    """
    s = str(s)
    if s == 'True' or s.lower() == 'yes':
        return True
    elif s == 'False' or s.lower() == 'no':
        return False
    else:
        raise(ValueError("input must be 'True'('yes') or 'False'('no')"))


def add_common_argument(parser):
    # common
    parser.add_argument('--outdir', default='default',
                        help='The directory of the output file, default is same with the input file')
    parser.add_argument('--force', '-f', action='store_true',
                        help='if set, overwriting file if output file exists')
    parser.add_argument('-g', is_write_out_config_file_arg=True,
                        help='save config to file path')
    parser.add_argument('-c', '--my-config', is_config_file_arg=True,
                        help='config file path')

# Cell
def rec_his(**kwargs):
    """
    return OrderedDict {'HISTORY+{time}': '{"key:value" in kwargs}'}
    """
    import json
    from datetime import datetime
    from collections import OrderedDict
    try:
        from ..__init__ import __version__
    except:
        __version__ = 'unknown'

    history = OrderedDict()
    history['version'] = __version__
    history['cwd'] = os.getcwd()
    history['argv'] = ' '.join(sys.argv)
    for key in kwargs.keys():
        history[key] = kwargs[key]
    current_time = datetime.now().strftime("%Y%m%d-%H:%M:%S")
    return OrderedDict({"HISTORY-"+current_time: json.dumps(history, indent=2)})

# Internal Cell
def add_extra(fin, _dict=None, fields_add=[]):
    """
    add some fields of fin to _dict
    """
    fields = ['is_on', 'next_to_cal', 'is_delay', 'Tcal', 'is_extrapo', 'vel']
    fields += fields_add
    out_add = {}
    for field in fields:
        if field in fin.keys():
            try:
                out_add[field] = fin[field][:]
            except:
                pass
    if _dict is None:
        return out_add
    else:
        _dict.update(out_add)

# Cell
def save_dict_hdf5(fname, dict_in, mode='w', spec2float32=True):
    """
    fname: str
    dict_in: dict; keys of the dict_in are str, value needs support slice, i.e. value[:].
             if 'Header':{...} in dict_in, save in attrs of group 'Header'
    spec2float32: default: True
             if True, convert 'Ta', 'flux', 'T' to float32
    """
    import h5py
    import numpy as np
    try:
        f = h5py.File(fname, mode)
    except OSError:
        if mode == 'w':
            from datetime import datetime
            os.rename(fname, fname+'.del.empty.'+datetime.now().strftime("%Y%m%d-%H%M%S"))
            f = h5py.File(fname, mode)
    for key in dict_in.keys():
        if key == 'Header':
            # sometimes hdf5 raises error if track_order = True
            header = dict_in['Header']
            f.create_group('Header', track_order=False)
            for key2 in header.keys():
                f['Header'].attrs[key2] = header[key2]
        else:
            if isinstance(dict_in[key], h5py.Dataset):
                f[key] = dict_in[key][:]
            elif spec2float32 and isinstance(dict_in[key], np.ndarray) and key in ['Ta', 'flux', 'T']:
                f[key] = dict_in[key].astype('float32')
            else:
                f[key] = dict_in[key]
    f.close()

# Cell
def load_hdf5_to_dict(fpath):
    """
    fpath: str
    """
    import h5py
    from collections import OrderedDict
    dict_out = {}
    fs = h5py.File(fpath, 'r')
    # load Header
    Header = OrderedDict()
    if 'Header' in fs.keys():
        try:
            Header.update(OrderedDict(fs['Header'].attrs.items()))
        except:
            print('input file have no Header')
    dict_out['Header'] = Header
    # load
    for key in fs.keys():
        if key != 'Header':
            dict_out[key] = fs[key][:]
    fs.close()
    return dict_out

# Cell
def get_nB(path):
    """
    return beam number deduced from "path"
    """
    return int(re.findall(r'-M[0-1][0-9]', os.path.basename(path))[-1][2:])


def replace_nB(path, nB):
    """
    replace the beam number of 'path' with the input nB
    path: str
    nB: int
    """
    return re.sub(r'[0-1][0-9]M-', f"-M{nB:02d}"[::-1], path[::-1], count=1)[::-1]


class BaseIO(object):
    """
    methods may need be replaced: _get_fpart, _import_m, gen_s2p_out, __call__, _get_out_basename
    """

    get_nB = staticmethod(get_nB)
    replace_nB = staticmethod(replace_nB)

    def __init__(self, args, dict_in=None, inplace_args=False):
        """
        args: class
              including attributes: fpath, outdir, frange
        dict_in: if None, load data from args.fpath, if set, omit data in args.fpath
        """
        self.args = args if inplace_args else copy.deepcopy(args)
        self.dict_in = dict_in
        self._gen_fpath_out()
        if self.dict_in is None:
            self._check_fout()
        self.nB = self.get_nB(self.args.fpath)
        self._import_m()
        self.open_fpath()
        self.load_radec()
        self.load_specs()
        self.load_and_add_Header()

    def _check_fout(self,):
        """
        check whether self.fout exists
        """
        args = self.args
        if os.path.exists(self.fpath_out):
            if args.force:
                print(f"will overwrite the existing out file {self.fpath_out}")
            else:
                print(f"File exists {self.fpath_out}")
                print("exit... Using ' --force ' to overwrite it.")
                sys.exit(0)

    def _gen_fpath_out(self,):
        """
        add self.fpath_out
        """
        args = self.args
        if args.outdir is None or args.outdir == 'default':
            args.outdir = os.path.dirname(args.fpath)
        self.fpath_out = os.path.join(args.outdir, self._get_out_basename())

    def _get_out_basename(self):
        """
        modify this fun to change out basename format
        """
        args = self.args
        fpart = self._get_fpart()
        return '.'.join(os.path.basename(args.fpath).split('.')[:-1]) + f'{fpart}.hdf5'

    def _get_fpart(self,):
        """
        need modify this function
        """
        return '-example'

    def _import_m(self,):
        """
        need modify this function
        """
        global h5py, OrderedDict
        import h5py
        from collections import OrderedDict

    def open_fpath(self,):

        self.fs = h5py.File(self.args.fpath, 'r') if self.dict_in is None else self.dict_in

    def close_fpath(self,):
        if self.dict_in is None:
            try:
                self.fs.close()
            except Exception as Err:
                print(Err)

    def load_radec(self,):
        args = self.args
        fs = self.fs
        if 'ra' in fs.keys() and 'dec' in fs.keys():
            self.ra = fs['ra'][:]
            self.dec = fs['dec'][:]
        elif not getattr(args, 'no_radec', False):
            try:
                from ..add_radec import get_radec
                nB_radec = getattr(args, 'nB_radec', 1)
                self.ra, self.dec, self.is_extrapo = get_radec(fs, nB_radec)
            except Exception as Err:
                print(Err)
        else:
            pass

    def load_specs(self,):
        """
        read mjd, freq, spectra(T or flux ) from self.fs
        load and add header
        """
        args = self.args
        fs = self.fs

        if 'T' in fs.keys():
            s2p = fs['T']
            outfield = 'Ta'
        elif 'Ta' in fs.keys():
            s2p = fs['Ta']
            outfield = 'Ta'
        elif 'flux' in fs.keys():
            s2p = fs['flux']
            outfield = 'flux'
            if getattr(args, 'flux', False):
                raise(ValueError(f'flux already exists, please remove \"--flux\" or set as False'))
        if getattr(args, 'flux', False):
            outfield = 'flux'
        self.s2p = s2p
        self.outfield = outfield

        self.mjd = fs['mjd'][:]
        self.freq = fs['freq'][:]
        self.freq_ori = self.freq
        if getattr(args, 'frange', False) and (args.frange[0] > 0. or args.frange[0] < float('inf')):
            self.is_use_freq = (self.freq >= args.frange[0]) & (self.freq <= args.frange[1])
            self.freq = self.freq[self.is_use_freq]
        else:
            self.is_use_freq = None

    def load_and_add_Header(self,):
        Header = OrderedDict()
        if self.dict_in is None:
            fs = self.fs
            if 'Header' in fs.keys():
                try:
                    Header.update(OrderedDict(fs['Header'].attrs.items()))
                except:
                    print('input file have no Header')
        else:
            if 'Header' in self.dict_in.keys():
                Header.update(self.dict_in['Header'])
        import json
        Header.update(rec_his(args=json.dumps(self.args.__dict__)))
        self.Header = Header

    def gen_dict_out(self, *args, **kwargs):
        """
        add self.ra, self.dec, self.mjd, self.freq
        add self.s2p to dict_out[outfield]
        add added field:
            self.add_fields = ['is_on', 'next_to_cal', 'is_delay', 'Tcal', 'is_extrapo', 'vel']
        add args in fpath file
        add key:value in kwargs
        add Header
        """
        dict_out = {}
        dict_out['mjd'] = self.mjd
        dict_out['freq'] = self.freq
        dict_out[self.outfield] = self.s2p_out
        # add field in add_fields and args from self.fs
        if not hasattr(self, 'add_fields'):
            self.add_fields = ['is_on', 'next_to_cal', 'is_delay', 'Tcal', 'is_extrapo', 'vel', 'is_rfi']
        self.add_fields += args
        for field in self.add_fields:
            if field in self.fs.keys():
                dict_out[field] = self.fs[field][:]
        # process vel if set frange
        if 'vel' in dict_out.keys() and self.is_use_freq is not None:
            dict_out['vel'] = dict_out['vel'][self.is_use_freq]
        # add ra dec
        for key in ['ra', 'dec', 'is_extrapo']:
            if hasattr(self, key):
                val_tmp = getattr(self, key)
                if val_tmp is not None:
                    dict_out[key] = val_tmp
        # add or replace from kwargs
        for key in kwargs.keys():
            dict_out[key] = kwargs[key]
        dict_out['Header'] = self.Header
        self.dict_out = dict_out

    def save(self,):
        print("Saving...")
        save_dict_hdf5(self.fpath_out, self.dict_out)
        print(f"Saved to {self.fpath_out}")

    def gen_s2p_out(self):
        """
        need modify this function
        """
        # process spectra
        if self.is_use_freq is None:
            self.s2p_out = self.s2p
        else:
            self.s2p_out = self.s2p[:][:, self.is_use_freq]

    def __call__(self, save=True):
        # store output data in self.dict_out
        self.gen_s2p_out()
        self.gen_dict_out()
        # save to hdf5 file
        if save:
            self.save()