# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core/beam.ipynb (unless otherwise specified).

__all__ = ['ConvFun']

# Cell
import numpy as np
from scipy import special
from functools import partial

# Cell
class ConvFun(object):
    def __init__(self, kernel_type, beam_fwhw, gaussian_fwhw=None,
                bsize=None, gsize=None):
        """
        kernel_type: str
            'gaussian':
            'bessel_gaussian':
            'sinc_gaussian':

        """
        if kernel_type == 'gaussian':
            if gaussian_fwhw is None:
                gaussian_fwhw = beam_fwhw/2
            sigma = gaussian_fwhw / (2*(2*np.log(2))**0.5)
            ConvFun.__call__ = staticmethod(partial(self.gaussian_kernel, sigma=sigma))
        elif kernel_type == 'bessel_gaussian':
            a = 1.55 * beam_fwhw / 3. if bsize is None else bsize
            b = 2.52 * beam_fwhw / 3. if gsize is None else gsize
            ConvFun.__call__ = staticmethod(partial(self.bessel_gaussian_kernel, a=a, b=b))
        elif kernel_type == 'sinc_gaussian':
            a = 1.55 * beam_fwhw / 3. if bsize is None else bsize
            b = 2.52 * beam_fwhw / 3. if gsize is None else gsize
            ConvFun.__call__ = staticmethod(partial(self.sinc_gaussian_kernel, a=a, b=b))
        else:
            raise(ValueError(f'kernel \"{kernel_type}\" is not supported'))

    @staticmethod
    def gaussian_kernel(dis, sigma):
        w = np.exp(-dis**2/(2*sigma**2))
        return w
    @staticmethod
    def bessel_gaussian_kernel(dis, a, b):
    #     a = 1.55 * beamsize / 3.
    #     b = 2.52 * beamsize / 3.
        x = np.pi*dis/a
        wei = np.empty_like(dis)
        not_zero = dis != 0
        wei[~not_zero] = 1 # peak value depend on the not_zero calculating method
        wei[not_zero] = 2*special.j1(x[not_zero])/(x[not_zero])*np.exp(-(dis[not_zero]/b)**2)
        return wei
    @staticmethod
    def sinc_gaussian_kernel(dis, a, b):
    #     a = 1.55 * beamsize / 3.
    #     b = 2.52 * beamsize / 3.
        x = np.pi*dis/a
        wei = np.empty_like(dis)
        not_zero = dis != 0
        wei[~not_zero] = 1
        wei[not_zero] = np.sin(x[not_zero])/(x[not_zero])*np.exp(-(dis[not_zero]/b)**2)
        return wei
