# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core/cal2.ipynb (unless otherwise specified).

__all__ = ['h5py_write', 'write_header', 'CalOnOffAA']

# Cell
import numpy as np
from matplotlib import pyplot as plt
from scipy import interpolate as interp
from scipy import ndimage

from .cal import *
from ..utils.io import MjdChanPolar_to_PolarMjdChan, gen_carta_group, save_specs_hdf5

from astropy.stats import sigma_clip

import warnings

# Cell
import h5py
import os
def h5py_write(fname, mode='w'):
    try:
        f = h5py.File(fname, mode)
    except OSError:
        if mode == 'w':
            from datetime import datetime
            os.rename(fname, fname+'.del.empty.'+datetime.now().strftime("%Y%m%d-%H%M%S"))
            f = h5py.File(fname, mode)
    return f


def write_header(f, header):
    f.create_group('Header', track_order=False)
    for key2 in header.keys():
        f['Header'].attrs[key2] = header[key2]

# Cell
class CalOnOffAA(CalOnOffA):

    def merge_pcals(self, pcals, method_merge='median', pre_process=False, exclued_franges=[]):
        """
        merging pcals at all time and smoothing it
        """

        if pre_process:
            amp = np.median(pcals, axis=1)
            pcals = pcals*(np.mean(amp, axis=0)/amp)[:,None,:]

        if method_merge == 'median':
            pcals_merged = np.median(pcals, axis=0, keepdims=True)
        elif method_merge == 'mean':
            pcals_merged = np.mean(pcals, axis=0, dtype='float64', keepdims=True)
        self.pcals_merged = pcals_merged
        self.pcals_merged_s = self._get_smoothed(pcals_merged)

    def pcals_amp_interp(self, inds_cal, pcals, squeeze_diff_freq='median', exclued_franges=None, method_interp='gaussian', sigma_t=600):
        """
        run self.merge_pcals first to get self.pcals_merged and self.pcals_merged_s
        gen self.pcals_amp_interp_values: the amplitude offset relate to mergred pcals, shape is (inds, polar)

        Parameters
        ----------
        squeeze_diff_freq: str; 'median', 'mean', 'sigclip_median', 'sigclip_mean'
        method_interp: str; 'gaussian' or kind in scipy.interpolate.interp1d
        exclued_franges: str; freq ranges which are not used in calculating amplitude offset; e.g. [[1375, 1385],]
        """
        if self.calc_diff_method == 'div':
            pcals_diff = pcals / self.pcals_merged_s
        elif self.calc_diff_method == 'sub':
            pcals_diff = pcals - self.pcals_merged_s
        else:
            raise(ValueError(f"self.calc_diff_method:{self.calc_diff_method}"))
        if exclued_franges is not None:
            is_not = np.full(len(self.freq_use), False)
            for (start, end) in exclued_franges:
                is_not |= ((self.freq_use > start) & (self.freq_use < end))
            pcals_diff = pcals_diff[:, ~is_not]
            self.freq_use_amp_interp = self.freq_use[~is_not]

        if squeeze_diff_freq == 'median':
            pcals_diff_m = np.nanmedian(pcals_diff, axis=1)
        elif squeeze_diff_freq == 'mean':
            pcals_diff_m = np.nanmean(pcals_diff, axis=1, dtype='float64')
        elif squeeze_diff_freq == 'sigclip_median':
            pcals_diff_m = np.nanmedian(sigma_clip(pcals_diff, axis=1, masked=False, return_bounds=False, copy=True), axis=1)
        elif squeeze_diff_freq == 'sigclip_mean':
            pcals_diff_m = np.nanmean(sigma_clip(pcals_diff, axis=1, masked=False, return_bounds=False, copy=True), axis=1)

        if method_interp == 'gaussian':
            t_sample = self.hduls[0][1].data['EXPOSURE'][0]
            sigma = sigma_t/((self.n_on+self.n_off)*t_sample)/(t_sample*self.n_on)
            fun = interp.interp1d(inds_cal, ndimage.gaussian_filter1d(
                pcals_diff_m, sigma, axis=0), fill_value="extrapolate", kind='quadratic', axis=0)
        else:
            # method_interp is one of "kind"
            fun = interp.interp1d(inds_cal, pcals_diff_m, fill_value="extrapolate", axis=0, kind=method_interp)
        self.pcals_amp_interp_values = fun(self.inds)

    def get_count_tcal(self, inds_on, inds_off):
        """
        run self.prepare_pcals first
        get count of tcal
        """
        #
        # interp cal power amp
        amp_interp_on = self.pcals_amp_interp_values[inds_on]
        amp_interp_off = self.pcals_amp_interp_values[inds_off]
        # load on and off power
        c_on = self.get_field(inds_on, 'DATA',).astype('float64')
        c_off = self.get_field(inds_off, 'DATA', close_file=True).astype('float64')
        #print(p_on.dtype, p_off.dtype, p_cal_s.dtype)
        if getattr(self, 'plot', False):
            figname = self.out_name_base + "-sep.pdf"
            plot_sep(inds_on, inds_off, c_on, c_off, figname=figname)
        # count as pcal
        if self.calc_diff_method == 'div':
            c_on /= (self.pcals_merged_s * amp_interp_on[:, None, :])
            c_on -= 1  # have subtracted cal
            c_off /= (self.pcals_merged_s * amp_interp_off[:, None, :])
        elif self.calc_diff_method == 'sub':
            c_on /= (self.pcals_merged_s + amp_interp_on[:, None, :])
            c_on -= 1  # have subtracted cal
            c_off /= (self.pcals_merged_s + amp_interp_off[:, None, :])

        return c_on, c_off

    def set_para_pcals(self, calc_diff_method='div', squeeze_diff_freq='median', method_interp='gaussian', sigma_t=600,
                       merge_cal_pre_process=False):
        """
        para used in self.prepare_pcals

        calc_diff_method: str; 'div', 'sub'
        """
        self.calc_diff_method = calc_diff_method # in self.pcals_amp_interp & self.get_count_tcal

        self.squeeze_diff_freq = squeeze_diff_freq
        self.method_interp = method_interp
        self.sigma_t = sigma_t
        self.merge_cal_pre_process = merge_cal_pre_process

    def prepare_pcals(self,):
        is_ = self.check_cal(self.inds_ton)
        pcals_use = self._get_cal_power(self.inds_ton[is_], self.inds_toff_bef[is_], self.inds_toff_aft[is_])
        self.merge_pcals(pcals_use, pre_process=self.merge_cal_pre_process)
        self.pcals_amp_interp(np.mean(self.inds_ton[is_], axis=1), pcals_use,
                              squeeze_diff_freq=self.squeeze_diff_freq,
                              method_interp=self.method_interp, sigma_t=self.sigma_t)
        return pcals_use, self.inds_ton[is_], self.inds_ton[~is_]

    def __call__(self, outdir='./', step=None, header=None, sep_save=False, save_p_cal=False, cali=True):
        """
        get T, mjd etc, and save in hdf5 file

        Parameters
        ----------
        outdir : str
            output directory
        step : int
            number of chunk files to process each time
        header : dict
            add in the output file
        sep_save : bool
            if True, save file every step.
        """
        #
        self.gen_out_name_base(outdir)
        n_step = self.lens[0]*step if step is not None else len(self.inds)
        inds_range = np.append(np.arange(0, self.inds[-1], n_step), self.inds[-1]+1)
        # inds_splited= np.array_split(self.inds, len(self.inds)//n_step)
        mjds = []
        extra = self.get_extra()
        # tcal
        tc_inter = self.get_Tcal_s() if cali else 'none'
        # update and write header
        header = {} if header is None else header.copy()
        if hasattr(self, 'tcal_file'):
            header.update({'tcal_file': self.tcal_file})
        # prepare for self.get_count_tcal

        self.plot = True

        if cali:
            pcals_use, inds_ton_use, inds_ton_not_use = self.prepare_pcals()
            if len(inds_ton_not_use)/(len(inds_ton_use) + len(inds_ton_not_use)) > 1/3.:
                warnings.warn('More than one-third of the Cals are abandoned. Please check your data and ``--pcal_vary_frac``.')
            if save_p_cal:
                p_cal_s_res = {}
                p_cal_s_res['inds_ton_use'] = inds_ton_use
                p_cal_s_res['inds_ton_not_use'] = inds_ton_not_use
                p_cal_s_res['pcals'] = pcals_use
                p_cal_s_res['pcals_merged'] = self.pcals_merged
                p_cal_s_res['pcals_merged_s'] = self.pcals_merged_s
                p_cal_s_res['pcals_amp_interp_values'] = self.pcals_amp_interp_values
                outname = self.out_name_base + '_p_cal_s.hdf5'
                print(f"p_cal in {outname}")
                p_cal_s_res['Header'] = header
                save_specs_hdf5(outname, p_cal_s_res)
                del pcals_use

        for i in range(len(inds_range)-1):
            print('part', i)
            b, e = inds_range[i:i+2]
            inds_on = self.inds_on[(self.inds_on >= b) & (self.inds_on < e)]
            inds_off = self.inds_off[((self.inds_off >= b) & (self.inds_off < e))]
            inds = np.hstack([inds_on, inds_off])
            sort = np.argsort(inds)
            mjd = self.get_field(inds[sort], field='UTOBS')  # have sorted

            if cali:
                count_tcal_res = self.get_count_tcal(inds_on, inds_off)
            else:
                count_tcal_res = [self.get_field(inds_on, 'DATA',), self.get_field(inds_off, 'DATA', close_file=True)]

            T = np.vstack(count_tcal_res[:2])
            del count_tcal_res
            if cali:
                T = T*tc_inter
            T = T[sort]  # sort T
            T = T.astype('float32')  # finally convert to float32

            if sep_save:
                res = {}
                for key in extra.keys():
                    res[key] = extra[key][inds[sort]]
                res['mjd'] = mjd
                res['freq'] = self.freq_use
                res['Ta'] = MjdChanPolar_to_PolarMjdChan(T)
                res['Tcal'] = tc_inter
                res['inds_ton_use'] = inds_ton_use
                res['inds_ton_not_use'] = inds_ton_not_use
                res['pcals_merged'] = self.pcals_merged
                res['pcals_merged_s'] = self.pcals_merged_s
                res['pcals_amp_interp_values'] = self.pcals_amp_interp_values[inds[sort]]

                # print(res)
                outname = self.out_name_base + f"-specs_T_{i:04d}_{i+1:04d}.hdf5"
                res['Header'] = header
                save_specs_hdf5(outname, res, wcs_data_name='Ta')
                print(f"Saved to {outname}")
                del res
            else:
                T = MjdChanPolar_to_PolarMjdChan(T)
                if i == 0:
                    outname = self.out_name_base + f"-specs_T.hdf5"
                    fout = h5py_write(outname)
                    #
                    fout.create_group('S')
                    g = fout['S']
                    # prepare writing spec
                    d_shape = list(T.shape)
                    d_shape[1] = len(self.inds)
                    g.create_dataset('Ta', shape=d_shape, dtype=T.dtype, chunks=True)
                g['Ta'][:, b:e, :] = T
                fout.flush()
                mjds += [mjd, ]
            self.plot = False  # only plot for the first loop
        # save other small data
        if not sep_save:
            write_header(fout, header)
            for key in extra.keys():
                g[key] = extra[key]
            g['mjd'] = np.hstack(mjds)
            g['freq'] = self.freq_use
            g['Tcal'] = tc_inter
            g['inds_ton_use'] = inds_ton_use
            g['inds_ton_not_use'] = inds_ton_not_use
            g['pcals_merged'] = self.pcals_merged
            g['pcals_merged_s'] = self.pcals_merged_s
            g['pcals_amp_interp_values'] = self.pcals_amp_interp_values

            print(f"Saved to {outname}")
            gen_carta_group(fout, g['Ta'].shape, wcs_data_name='Ta', axis1=g['freq'], axis2=g['mjd'])
            fout.close()
