# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core/flux.ipynb (unless otherwise specified).

__all__ = ['get_ratio', 'Calibrator', 'FluxCali']

# Cell

import os
import re
from glob import glob

import h5py
import numpy as np
import scipy.interpolate as interp
from astropy.time import Time
from astropy import units

from .gain import Get_gain, gain_diff_from_ZA, Get_ZA

# Cell
def get_ratio(nB, freq=None):
    """get gain ratio to beam 1 in arXiv:2002.01786"""
    import pandas as pd
    ratios_para = pd.read_json(os.path.dirname(__file__) + '/data/beam_ratios.json')

    freq_key = np.array(ratios_para.index[::2], dtype=float)
    ratios = ratios_para[f'M{nB:02d}'][::2].values
    if freq is not None:
        ratios= interp.interp1d(freq_key,ratios, kind='quadratic', fill_value= "extrapolate")(freq)
        freq_key=freq
    return ratios, freq_key

# Cell
class Calibrator:

    def __init__(self, mjd, nB, cbr_store, cbr_name='*', use_counts=True, only_use_19beams=False):
        """
        mjd: used to find nearest cbr
        nB: beam number
        cbr_store: str
           where quasar calibrator stored in, a file path or a directory including several files
           If None, use the gain depended on Zenith angle (arxiv:2002.01786) and need input ra, dec and mjd.
        cbr_name: str, e.g. 3C48
           If not None and cbr_store is a directoy, searching the specified calibrator.
        use_counts: bool
           If True, return gain as counts/Jy, If False, K/Jy
        """
        self.cbr_store = cbr_store
        self.cbr_name = cbr_name
        self.mjd = mjd
        self.nB = nB
        self.use_counts = use_counts
        self.only_use_19beams = only_use_19beams
        self.parser_cbr()

    @staticmethod
    def get_date_nearest(fpath_list, mjd):
        dates_have = [os.path.basename(fpath).split('-', 2)[1] for fpath in fpath_list]
        dates_have = [f'{s[:4]}-{s[4:6]}-{s[6:8]} {s[8:10]}:{s[10:12]}:00.000' for s in dates_have]
        mjds_h = (Time(dates_have, format='iso', scale='utc') - 8*units.hour).mjd
## use mjd
#         mjds_h = np.empty(len(fpath_list), dtype='float64')
#         for i, fpath in enumerate(fpath_list):
#             with h5py.File(fpath) as fs:
#                 mjds_h[i] = fs['mjd'][0]
        ind = np.argmin(abs(mjds_h - mjd))
        return fpath_list[ind]

    def _calc_ratio(self, fpath):
        """calc gain ratio to beam 1"""
        with h5py.File(fpath, 'r') as fs:
            freq = fs['freq'][()]
            K_Jy = fs[f'M{self.nB:02d}'][0]
            K_Jy_nB1 = fs[f'M01'][0]
#             print(K_Jy,K_Jy_nB1)
            ratio = K_Jy/K_Jy_nB1
            if self.use_counts:
                Tcal = fs[f'Tcal{self.nB}'][0]
                Tcal_nB1 = fs[f'Tcal1'][0]
                ratio /= (Tcal/Tcal_nB1)
        return freq, ratio

    def get_ratio(self):
        # cbr_store is directory
        fpaths_nB_all = glob(os.path.join(self.cbr_store, f"{self.cbr_name}-20*-FluxGain-All.hdf5"))
        if len(fpaths_nB_all) == 0:
            raise(ValueError('can not find 19-beams calibration file to calculate relative gain'))
        else:
            fpath = self.get_date_nearest(fpaths_nB_all, self.mjd)
            print(f"using {fpath} to calculate relative gain to M01")
            freq, ratio = self._calc_ratio(fpath)
        return freq, ratio

    def parser_cbr(self,):
        """assign or serach fpath from self.cbr_store"""
        if not os.path.exists(self.cbr_store):
            raise(ValueError(f'can not find the calibrator: {self.cbr_store}'))
        if os.path.isfile(self.cbr_store):
            self.cbr_fpath = self.cbr_store
        else:
            if self.only_use_19beams:
                fpaths_cand = glob(os.path.join(self.cbr_store, f"{self.cbr_name}-20*-FluxGain-All.hdf5"))
            else:
                fpaths_cand = glob(os.path.join(self.cbr_store, f"{self.cbr_name}-20*-FluxGain*.hdf5"))
            if len(fpaths_cand) == 0:
                raise(ValueError(f"can not find calibrator file"))
            self.cbr_fpath = self.get_date_nearest(fpaths_cand, self.mjd)

    def get_ZA_cbr(self, fs, nB):
        if f'ZA{nB}_cbr' in fs.keys():
            ZA = fs[f'ZD{nB}_cbr'][()]
        else:
            ZAs = fs[f'ZD{nB}'][()]
            ZA = np.mean(ZAs)
        # need deg
        ZA = np.rad2deg(ZA)
        return ZA

    def __call__(self, freq_new=None, ZAs_obs=None):
        """
        freq_new: if not None, will interplate
        ZAs_obs: ZA of obs spec. If not None, will fix the gain diff from ZA diff
        """
        print(f'loading gain from {self.cbr_fpath}')
        with h5py.File(self.cbr_fpath) as fs:
            freq = fs['freq'][()]
            key_ = f'M{self.nB:02d}'
            if freq_new is None:
                freq_new = freq
            # fix ZA diff
            if key_ in fs.keys():
                gain = fs[key_][()] # K/Jy, shape:(1, chan, 2)
                gain = interp.CubicSpline(freq, gain, axis=1, extrapolate=True)(freq_new)
                if ZAs_obs is not None:
                    diff = gain_diff_from_ZA(self.get_ZA_cbr(fs, self.nB), ZAs_obs, self.nB, freq_new)
                    gain = gain + diff[..., None]
                if self.use_counts:
                    tcal = fs[f'Tcal{self.nB}'][()]
                    tcal = interp.CubicSpline(freq, tcal, axis=1, extrapolate=True)(freq_new)
                    gain /= tcal # to count of tcal i.e. Counts/Jy
            else:
                # use M01 or relative gain ratio
                gain_nB1 = fs[f'M01'][()] # K/Jy
                gain_nB1 = interp.CubicSpline(freq, gain_nB1, axis=1, extrapolate=True)(freq_new)
                if ZAs_obs is not None:
                    diff = gain_diff_from_ZA(self.get_ZA_cbr(fs, 1), ZAs_obs, 1, freq_new)
                    gain_nB1 = gain_nB1 + diff[..., None]
                if self.use_counts:
                    tcal = fs[f'Tcal1']
                    tcal = interp.CubicSpline(freq, tcal, axis=1, extrapolate=True)(freq_new)
                    gain_nB1 /= tcal # Counts/Jy
                freq_ratio, ratio = self.get_ratio()
                ratio = interp.CubicSpline(freq_ratio, ratio, extrapolate=True)(freq_new)
                gain = gain_nB1 * ratio[None,:]
        return freq_new, gain

# Cell

class FluxCali:

    def __init__(self, nB, freq, cbr_store=None, cbr_name='*', tcal_spec=None,  only_use_19beams=False,
                           mjd=None, ra=None, dec=None, ZAs=None, fix_diff_ZA=False):
        """

        flux calibration using Calibator or Table Gain
        -----------------------
        T: array_like
           Temperature of the spectra. Shape is (m,n) or (m,n,2) i.e. (Mjd, channel) or (Mjd, channel, Polarization)
        nB: int
           Beam numbe
        freq: array_like, shape (n,)
        cbr_store: str
           where quasar calibrator stored in, a file path or a directory including several files
           If None, use the gain depended on Zenith angle (arxiv:2002.01786) and need input ra, dec and mjd.
        cbr_name: str, e.g. 3C48
           If not None and cbr_store is a directoy, searching the specified calibrator.
        tcal_spec: shape: (1,n,2); T.shape need be (m,n,2); if spectra and Calibator temperature used different Tcal, input this to fix it.
        ra, dec, mjd: None or array_like, shape (m,)

        """

        if ra is not None and dec is not None:
            if np.isscalar(mjd):
                mjd = np.array([mjd])
            if np.isscalar(ra):
                ra = np.array([ra])
            if np.isscalar(dec):
                dec = np.array([dec])
            assert ra.shape[0] == dec.shape[0] == mjd.shape[0]

        self.nB = nB
        self.freq = freq
        self.cbr_store = cbr_store
        self.cbr_name = cbr_name
        self.tcal_spec = tcal_spec
        self.only_use_19beams = only_use_19beams
        self.mjd = mjd

        self.ra = ra
        self.dec = dec
        self.ZAs = ZAs
        self.fix_diff_ZA = fix_diff_ZA

        if cbr_store is None or cbr_store=='none':
            self.K_Jy = self.get_gain_tabled()
        else:
            self.K_Jy = self.get_gain_cbr()

    def get_gain_cbr(self,):

        use_counts = True if self.tcal_spec is not None else False

        CBR = Calibrator(np.mean(self.mjd), self.nB, self.cbr_store,
                         use_counts=use_counts,
                         only_use_19beams=self.only_use_19beams)
        if self.fix_diff_ZA:
            if self.ZAs is not None:
                ZAs = self.ZAs
            else:
                ZAs = Get_ZA(self.ra, self.dec, self.mjd)
        else:
            ZAs = None
        _, gain = CBR(self.freq, ZAs)
        self.cbr_fpath = CBR.cbr_fpath
        K_Jy = gain * self.tcal_spec if use_counts else gain
        return K_Jy


    def get_gain_tabled(self,):

        K_Jy = Get_gain(self.ra, self.dec, self.mjd, self.nB, self.freq)[0]  # K/Jy

        return K_Jy[:, :, None]

    def __call__(self, T):
        """
        T: array; shape: (Mjd,Chan,Polar) or (Mjd,Chan)
        """
        K_Jy = self.K_Jy
        # cali
        if T.ndim == 2:
            return T/np.mean(K_Jy, axis=2)
        elif T.ndim == 3:
            if T.shape[-1] == 2:
                return T/K_Jy
            elif T.shape[-1] == 1:
                return T/np.mean(K_Jy, axis=2, keepdims=True)
            else:
                raise(ValueError('shape of T'))
        else:
            raise(ValueError('shape of T'))
