# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core/regions.ipynb (unless otherwise specified).

__all__ = ['read_regions', 'box', 'line', 'replace_region']

# Cell
import warnings
import math
import numpy as np

# Cell
def read_regions(fpath):
    with open(fpath, 'r') as f:
        # skip comment
        line = f.readline().strip()
        while line:
            if line.startswith('#'):
                line = f.readline().strip()
            else:
                break

        if not line.startswith('global'):
            warnings.warn(f"format error in {fpath}, the first line not started with '#' should start with 'global'. ")
            return None
        # region unit
        line = f.readline().strip()
        if not line:
            warnings.warn(f"no region found in {fpath}")
            return None
        elif line != 'physical':
            warnings.warn(f"only 'physical' type regions are supported, please check {fpath}")
            return None
        # read region
        regions = {}
        line = f.readline().strip()
        while line:
            key, remain = line.split('(', 1)
            reg = tuple(map(float, remain.split(')', 1)[0].split(',')))
            if key in regions:
                regions[key] += [reg, ]
            else:
                regions[key] = [reg, ]
            line = f.readline().strip()
        return regions

# Cell
def box(center_x, center_y, size_x, size_y, PA=None):
    """
    box: (center_x, center_y, size_x, size_y, PA?)
    """
    bottom_left = center_x - size_x/2, center_y - size_y/2
    top_right = center_x + size_x/2, center_y + size_y/2

    bottom_left = [max(math.ceil(num), 0) for num in bottom_left]
    top_right = [max(math.floor(num), 0) for num in top_right]

    return slice(bottom_left[0], top_right[0]+1), slice(bottom_left[1], top_right[1]+1)

# Cell
def line(start_x, start_y, end_x, end_y):
    """
    line(start_x, start_y, end_x, end_y)
    """

    dx_abs = abs(start_x - end_x)
    dy_abs = abs(start_y - end_y)

    if dx_abs > dy_abs:
        s = max(math.ceil(min(start_x, end_x)), 0)
        e = max(math.floor(max(start_x, end_x)), 0)
        return slice(s, e+1), slice(None)
    else:
        s = max(math.ceil(min(start_y, end_y)), 0)
        e = max(math.floor(max(start_y, end_y)), 0)
        return slice(None), slice(s, e+1)

# Cell
def replace_region(arr, regions, fill_value=np.nan, inplace=True):
    """
    arr: array; ndim >=2, slice the first two dim to replace
    regions:
    fill_value:
    inplace:
    """

    if not inplace:
        arr = np.copy(arr)
    for key in regions.keys():
        if key == 'box':
            for reg in regions[key]:
                arr[box(*reg)[::-1]] = fill_value # x axis is freq
        elif key == 'line':
            for reg in regions[key]:
                arr[line(*reg)[::-1]] = fill_value
        else:
            warnings.warn(f'region type {key} not support')
    return arr
