## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --rms_frange; default: [0,0];freq range to compute rms, NEED TO DEFINE when sf, pdr 
rms_frange = [1390, 1400]
#help: --mw_frange; default: ;milky way freq range
mw_frange = [1420.2, 1420.45]
#help: --rms_sigma; default: 6; gauss filter sigma to compute real rms
rms_sigma = 6

## *Time domain continuous RFI
## ##########################################################################
#help: --tr, --time_rfi; default: False; choices: True, False; 
tr = False
#help: --tr_s_method_t; default: gaussian; smoothing method along time axis
tr_s_method_t = gaussian
#help: --tr_s_sigma_t; default: 10; 
tr_s_sigma_t = 10
#help: --tr_s_method_freq; default: gaussian; smoothing method along time freq
tr_s_method_freq = gaussian
#help: --tr_s_sigma_freq; default: 5; 
tr_s_sigma_freq = 5
#help: --tr_n_continue; default: 100; 
tr_n_continue = 100
#help: --tr_times; default: 6.0; 
tr_times = 6.0
#help: --tr_times_s; default: 1.5; 
tr_times_s = 1.5
#help: --ext_add; default: 0; extend rfi range
ext_add = 0
#help: --ext_frac; default: 0.0; between 0 and 1, extend rfi range
ext_frac = 0.0

## *Narrowband single channel RFI
## ##########################################################################
#help: --nr, --narr_rfi; default: True; choices: True, False; find long time narrow single channel rfi
nr = False
#help: --nr_mean_times; default: 100; first threhold, rfi is this times of median value after mean along time axis; \
#                   if --lsn_thr_type == 'input_thr', input mean_thr here."
nr_mean_times = 100
#help: --nr_diff_times; default: 30; second threhold, sharp edge on time axis. diff above this times of median will be recognized; \
#                   if --lsn_thr_type == 'input_thr', input diff_thr here.
nr_diff_times = 30

## *Polarized RFI
## ##########################################################################
#help: --pr, --polar_rfi; default: False; choices: True, False; 
pr = True
#help: --pr_s_sigma; default: 5; gaussian smooth size for spectra smoothing along time axis
pr_s_sigma = 5
#help: --pr_times; default: 6; 
pr_times = 6
#help: --pr_times_s; default: 1; 
pr_times_s = 1.5

## *Long freq 
## ##########################################################################
#help: --lf, --long_freq; default: False; choices: True, False; find time rfi
lf = False
#help: --lsn_thr_type; default: input_med_times; choices: input_med_times, input_thr; \
#                         input times of median value or threshold directly. used for lf, sf, nr
lsn_thr_type: input_med_times
#help: --lf_frange; default: [1400, 1500];freq range exists long-freq time rfi
lf_frange = [1400, 1460]
#help: --lf_mean_times; default: 2; first threhold, rfi is this times of median value after mean along time axis; \
#                   if --lsn_thr_type == 'input_thr', input mean_thr here.
lf_mean_times = 2
#help: --lf_diff_times; default: 0; set 0 and do not change this parameter
lf_diff_times = 0
#help: --lf_rfi_last; default: 50; rfi lasts at least 20 spec numbers
lf_rfi_last = 50
#help: --lf_ext_add; default: 50; extend edge
lf_ext_add = 100

## *Short freq 
## ##########################################################################
#help: --sf, --short_freq; default: False; choices: True, False; find time rfi
sf = True
#help: --sf_frange; default: [1370, 1390];freq range exists short-freq time rfi
sf_frange = [1379.5,1383]
#help: --sf_frange_step; default: ; if sf_frange is None and sf_file is None, cycle in whole freq band.
#sf_frange_step = 30
#help: --sf_file; default: ;freq range exists short-freq time rfi npy filename
#sf_file = 
#help: --sf_mean_times; default: 3; first threhold, rfi is this times of median value after mean along time axis; \
#                   if --lsn_thr_type == 'input_thr', input mean_thr here."
sf_mean_times = 3
#help: --sf_diff_times; default: 1; second threhold, sharp edge on time axis. diff above this times of median will be recognized; \
#                   if --lsn_thr_type == 'input_thr', input diff_thr here.
sf_diff_times = 10
#help: --sf_rfi_last; default: 10; rfi lasts at least 10 spec numbers
sf_rfi_last = 20
#help: --sf_ext_add; default: 0; extend edge
sf_ext_add = 0

## preprocessing before finding pdr
#help: --s_method_t; default: none; choices: none, gaussian, boxcar, median; 
s_method_t = boxcar
#help: --s_sigma_t; default: 5; 
s_sigma_t = 7
#help: --s_method_freq; default: none; choices: none, median, gaussian, boxcar; 
s_method_freq = gaussian
#help: --s_sigma_freq; default: 5; 
s_sigma_freq = 3

## *find Period 8MHz 
## ##########################################################################
#help: --pdr, --period_rfi; default: False; choices: True, False; find period 8 MHz rfi
pdr = True
#help: --rfi_thr; default: 3; default 3 times of rms threshold
rfi_thr = 15
#help: --rfi_width_lim; default: 10; rfi should contain more channels than limit
rfi_width_lim = 20
#help: --ext_sec; default: 30; extend channel number of start and end of each section
ext_sec = 20
#help: --freq_thr; default: 0.5; estimate error when looking for peaks to polyfit
freq_thr = 0.5
#help: --freq_step; default: 8.1; rfi period MHz
freq_step = 8.1
#help: --rfi_groups; default: two_groups; choices: two_groups, three_groups, all; divide rfi into 2 or 3 groups
rfi_groups = two_groups

## mask 8 Mhz RFI
#help: --mask_RFI_method; default: fixed_freq; choices: 2_sides, fixed_freq; from center to two sides, or use a fixed freq width
mask_RFI_method = fixed_freq
#help: --freq_from_theory; default: 0.5; mask width from theory center
freq_from_theory = 0.5
#help: --mask_thr; default: 0.7;  above ~ times of rms threshold will be masked
mask_thr = 0.7
#help: --ext_edge; default: 0;  extend result channel on freq axis
ext_edge = 2
#help: --small_rfi_times; default: 2; small rfi below, eg.2*RMS will not be masked
small_rfi_times = 2
#help: --chan_step; default: 5; channel step when walk from center to two sides
chan_step = 1
#help: --mask_all_theory; default: False; mask_all_theory
#mask_all_theory
#help: --time_coherent_per; default: 1; rfi in one freq appears more than emmm, maybe 70%%, mask them all on time axis.
time_coherent_per = 1

