## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --frange; default: [0, inf]; Limit frequence range
frange = [0, inf]

## *BaseLine (set --method as none to skip this) 
## ##########################################################################
#help: --method; default: arPLS; choices: none, arPLS, srPLS, Chebyshev, poly, original; method used to fit baseline, if set as none, skip this
method = arPLS
#help: --nproc, -n; default: 1; number of process used in fitting baseline
nproc = 10

## preprocessing before baseline fitting
#help: -T, --trans; default: False; choices: True, False; 
trans = False
#help: --njoin; default: 0; join spectra (average) to fit same baseline
njoin = 0
#help: --s_method_t; default: none; choices: none, gaussian, boxcar, median; method used to smooth every channel along time axis
s_method_t = none
#help: --s_sigma_t; default: 5; used with --s_method_t
s_sigma_t = 5
#help: --s_method_freq; default: none; choices: none, median, gaussian, boxcar, PLS, fft; method used to smooth every spectrum along frequency axis
s_method_freq = gaussian
#help: --s_sigma_freq; default: 5; used with --s_method_freq
s_sigma_freq = 5
#help: --average_every_freq; default: 0; 
average_every_freq = 0

## fit and subtract the baseline
#help: --lam; default: 100000000.0; baseline fit parameters
lam = 1e12
#help: --deg; default: 2; baseline fit parameters
deg = 2
#help: --offset; default: 2; baseline fit parameters
offset = 2
#help: --ratio; default: 0.01; baseline fit parameters
ratio = 0.01
#help: --niter; default: 100; baseline fit parameters
niter = 100

