## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --frange; default: [0, inf]; Limit frequence range
frange = [1300, 1440]

## *Flux
## ##########################################################################
#help: --cali_fname; default: none; calibration source file name
cali_fname = none